### ISSUE TITLE
Stylebot does not work with https://mail.google.com/tasks/canvas

### ISSUE THREAD

**Issue by roxaneai** [ankit/stylebot#136]
Dear,

I have tried stylebot to modify Google Tasks page, however it does not work.

Please test this URL: https://mail.google.com/tasks/canvas.

Thanks,

**Comment by b9chris** [comment]
I'm having the same issue here. I'm unclear on how StyleBot is meant to be used on iframe content.

1) Should the URL pattern be for the URL of the iframe, or the URL of its containing page?

2) Do I need to do anything special to tell Stylebot to look inside iframe(s)?

Here's an example: In Gmail if you use Chat, there are chat boxes with a Video Call button at the top. If you ever press this button by accident, you interrupt someone else, seriously upsetting them, for no reason. This is common. I want it gone.

If I open a Chat as a separate window this is trivial:

hangouts.google.com
div.ttmkl {
    display: none;
}

And it works in StyleBot. As soon as I collapse it back into Gmail, it's now in an iframe and not found by StyleBot. This is regardless of whether I use the URL pattern for the iframe (hangouts.google.com) or Gmail (mail.google.com).

How do I get this to work?

I'm unclear on whether this is a continuation of this bug or just missing documentation.

**Comment by mitcheal** [comment]
@b9chris styling google gmail tasks bar because its an iframe you'll need to reference the iFrame URL.  As of today targeting https://tasks.google.com  works for me.

For anyone looking for Dark Mode CSS as of today this is working for me:

`.SSPGKf {
	background: #090909;
}
.uqJv0c {
	background-color: #111111;
	border-bottom: solid 1px #373737;
}
.PV0kIb {
	background-color: #090909;
  margin-bottom: 20px;
}
.lq5Efd {
	background-color: #000000;
	border: 1px solid #000000;
}
.bRcSk .c6ZeFd, .bRcSk .RFmU6c {
	color: #d6d6d6;
}
.zRfOtf {
	background-color: #000000
}
.NNKXjd {
	background-color: #000000;
	color: #707070;
}
.NNChOb {
    border-top: 1px solid #000000;
}

.PwTVze .Pf0ADe {
    border-bottom: 1px solid #000000;
    box-sizing: border-box;
}`
