### ISSUE TITLE
Login via facebook won't work on Social

### ISSUE THREAD

**Issue by bykbtzr** [ankit/stylebot#158]
Since last week I've been trying log in via my facebook account to update one of my styles, but when the FB popup closes I'm just get redirected to the Social home page.
If this problem is specific to my account, is there someway to put the styles of my FB account into my registred account?

Thanks

**Comment by kbtzr** [comment]
Due to recent events I'm removing my old username from my old comments for privacy concerns. 
@ankit Could you redact it out from your comment as well? That would be very kind of you, thanks!
