### ISSUE TITLE
[Bug] Stylebot Styling Frame Doesn't Appear

### ISSUE THREAD

**Issue by skyadd** [ankit/stylebot#161]
Chrome Latest DEV version: 18.01010.1 dev-m
## Windows 7 Operating System

The stylebot popup frame doesn't appear under any circumstances, including when I click on the "CSS" icon in the omnibar or choose "Style Element" from the right-click context menu.

This happens in all instances of chrome I've run to test this-- including on different profiles, incognito mode, new installs of the extension, reinstalls of the extensions.

All other aspects of the addon- including the extension "options" - seem to work fine.

**Comment by Arinerron** [comment]
I'm still having this issue and I am completely updated in Chrome and OS and plugin.
