### ISSUE TITLE
!important

### ISSUE THREAD

**Issue by madsynn** [ankit/stylebot#170]
I have a request and a idea that might work on this matter. How about you add a ! button to the control panel and when someone does not want it they un click it. I would also like to see it in the (edit) screen instead of hiding it so you can copy and paste true css to use on your development.   As it is right now you have to go and add it into the template or style you are working on to override and its just a pain.   Examples would be for editing existing themes in Wordpress or Joomla.. Just a idea that would make a lot of our lives easier.

**Comment by fenhl** [comment]
Any updates on this?

**Comment by MichaelZalla** [comment]
+1 I'd like to see '!important' rules supported as well, if only to override existing '!important' rules on the page(s) you are trying to modify.

**Comment by maxomaniak** [comment]
+1 on this, when I add !important after a line it gets deleted automatically.

**Comment by Fordi** [comment]
This is especially relevant with global styles, in which `!important` is added whether it's in the global sheet or not.

Use case, for general site performance, I want to set the defaults for `image-rendering` and `font-rendering` to `pixelated` and `optimizeSpeed`, respectively - however if I do this, sites that explicitly set these properties are not overridden - even where they are important (e.g., in a micro-app that does image scale/crop/trim/pad, or a site that uses a custom font for its iconography, these might be set to `optimizeQuality` or `geometricPrecision`, and for good reason).

**Comment by tdechangy** [comment]
After such a long timed request, could you please consider this option. This would make your plugin a definite Designer's killer tool !!! It will allow to gain so much time remove the efforts to go back and forth just to see how to adjust the code.

Looking forward for your clever upgrades.
Best.

**Comment by No5972** [comment]
So this issue has been put forward since 2012?

I am considering removing this "!important" function by myself...
