### ISSUE TITLE
not working on google sites

### ISSUE THREAD

**Issue by ghost** [ankit/stylebot#184]
The style I've already typed in is still working, but the interface for stylebot will not come up correctly on google.com or gmail.com. on google, using the "css" button in the omnibar brings up the stylebot interface as text only, along the left side, and pretty unusable (its setup to be on the right). in gmail, it does the same thing, only the omnibar button doesn't work, i have to right-click an element and click style element. 

every once in a while i get lucky and the UI comes up, but only the bottom half of the basic ui shows up. the top half is supposed to be the CSS editor but has no edit box, and the mode buttons (basic, advanced, edit css) don't work.

even less than that, sometimes it actually does come up correctly when i click style element. but this rarely happens, when it does, i take as much advantage as i can and keep it open for 2 days straight.

im on chrome beta 24.0.1312.14

EDIT: it was working fine on other sites, but i just tested again and its doing like it does for google.com, so now its pretty much completely unusable.

**Comment by StLa1** [comment]
Doesn't open on Gmail
