### ISSUE TITLE
Support enabling/disabling of styling from browser action menu

### ISSUE THREAD

**Issue by gth** [ankit/stylebot#195]
Can a middle-mouse click (i.e. pressing the mousewheel) on the omni bar CSS icon of Stylebot be made to toggle styling being enabled (or disabled) ?

PS: Also, since the context menu option "Enable Styling" words do not change when actually enabling or disabling styling, perhaps it should be worded as "Toggle Styling" ?

**Comment by ankit** [comment]
this is now implemented.
