### ISSUE TITLE
!important decleration vanishes

### ISSUE THREAD

**Issue by Austinuity** [ankit/stylebot#226]
The !important declaration always seems to vanish for me when I add it.

**Comment by ssbarnea** [comment]
This bug should be reopen. is true the `!important` is removed and this confuses the users. At least you could put a comment in the edit window saying that `!important` is removed.

I was trying to debug why CSS was not working and this made me lose a lot of time.

**Comment by ChrisLang** [comment]
@ ssbarnea, its been three years, take a look @ Stylish. They shouldnt be adding a !important declaration at all anyways, should be loading the stylesheet at the bottom of the doc to override exsiting styles IMO.

**Comment by ChrisLang** [comment]
@ankit excuse my ignorance, but is there a viable reason as to why the css properties require an !important declaration? I see the styles been added @ the end of the document, so why not leave the css to cascade as its designed to

**Comment by eye-sigil** [comment]
Guys, the repo's dead. Fork it and get it over with.
