### ISSUE TITLE
[Feature Request] sync styles across Chrome instances

### ISSUE THREAD

**Issue by dcormier** [ankit/stylebot#230]
I use stylebot at home and at work. It's kind of annoying to have to manually sync my custom styles. It would be nice if the extension handled this.

One suggestion would be take advantage of the ability to sync extension storage. See here: http://developer.chrome.com/extensions/storage.html#property-sync

**Comment by Kccool2** [comment]
How are we doing on this feature?

**Comment by mattcoady** [comment]
Also looking for this

**Comment by Kccool2** [comment]
Any news on progress ankit? Really hoping this feature is implemented! It would really push stylebot to the next level!

**Comment by ogny** [comment]
It will be appreciated if you would do it

**Comment by js365** [comment]
Please support the sync feature. This is the only extension I'm using needs to sync manually.
I really love this extension.

**Comment by ectoanonymous** [comment]
Any progress with this?

**Comment by ectoanonymous** [comment]
Still not supported? It is the only extension of all which I use which do not support chrome sync....Pls integrate this feature into this extension....

**Comment by ankit** [comment]
I will fix add `sync` capability in the v3 re-write, thank you.

**Comment by ankit** [comment]
Update - I researched support for sync in extensions and it actually has a stringent quota that won't work for stylebot (https://developer.chrome.com/extensions/storage#property-sync). As a result, this didn't make the v3 release. 

However, I do plan to figure out an approach and implement this in a future release, since it would be really useful.

**Comment by sebdybowski** [comment]
@ankit that would be great, looking forward to see it in the plugin!

**Comment by robbyking** [comment]
Has there been any movement on this? I'd be happy to contribute.

**Comment by ankit** [comment]
The first iteration on this will be arriving in the next release. It will allow syncing across multiple instances of Chrome/Firefox via Google Drive OAuth (this can later be extended to other services such as github as well). 

The other caveat is that it will be manual - you will have to click on "Sync Now" via the popup (it will take quite a bit more work to enable auto-sync by building a server that uses OAuth in `offline` mode with refresh tokens to auto-generate the access token). Seems to work well even with this limitation.  

<img width="368" alt="Screen Shot 2021-04-12 at 9 36 15 PM" src="https://user-images.githubusercontent.com/61857/114497740-a5fc9580-9bd7-11eb-8b63-b468b48e7059.png">

**Comment by ankit** [comment]
Merged. will be included in [v3.1](https://github.com/ankit/stylebot/milestone/8)

**Comment by hab25** [comment]
> Update - I researched support for sync in extensions and it actually has a stringent quota that won't work for stylebot ([developer.chrome.com/extensions/storage#property-sync](https://developer.chrome.com/extensions/storage#property-sync)). As a result, this didn't make the v3 release.
> 
> However, I do plan to figure out an approach and implement this in a future release, since it would be really useful.

What part of that quota is a limiting factor for stylebot? The numbers seemed large enough for my usage, and having the automatic sync would be much more convenient than the manual (button-clicking) method.
