### ISSUE TITLE
Favorite styles for a given page to reference them easily

### ISSUE THREAD

**Issue by mhuebert** [ankit/stylebot#239]
Until today, I used the "Enable styling..." option to temporarily disable my Stylebot style. This option perhaps had a confusing name, but it was very useful and I made use of it daily.

Now, it seems I must reset the page to see the original. But this is a permanent change. To 'revert' to the styled element, I need to hunt through "Install from social.." to find the original (thankfully I _saved_ my style here, otherwise I believe it would be gone forever?).

It would be nice (a) to have a way to toggle Stylebot on/off for a given page, and/or (b) save 'favorite' styles for a given page to reference them easily. (unless I am missing something?)

**Comment by ankit** [comment]
there is now an easy way to enable/disable styles for a page from the popup menu
