### ISSUE TITLE
Trying to write a rule with :nth-child crashes tab after writing opening parenthesis

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [ankit/stylebot#249]
Pretty much what the title says :)

To reproduce, open any page, say google.com. Then open Stylebot, go to Edit CSS, and then write any selector with an nth-child in it, such as
    div:nth-child(
That's how far you get. The tab then freezes, and after a bit, you get "It's dead, Jim".

Cheers,
Daniel

**Comment by JiRybar** [comment]
This bug still persists.

**Comment by flatline-studios** [comment]
Still here... As a workaround, if you write your selector out in full... Like:

`.ms-Fabric > div:nth-of-type(2) > div > div:first-of-type > div:last-of-type { display: none; }`

Then it will still work as expected. You just can't type it in to the box for some reason. There's likely an OnChange event firing in the editor textbox that's getting caught in a recursive loop, and eventually OOMing the tab.
