### ISSUE TITLE
Feature Request: Support Media Queries in "Edit CSS" mode

### ISSUE THREAD

**Issue by mkspeakman** [ankit/stylebot#264]
Add StyleBot support for media queries in "edit css," such as:

@media only screen and (min-width: 768px) {
<h1>font-size:2em;"
}

**Comment by mesqueeb** [comment]
It gives me a syntax error with @media print......
Can this be fixed?

**Comment by jm3** [comment]
looks like this is still an issue :(

**Comment by Maxime-cn** [comment]
As this been corrected? 3 years later I still do not manage to use media queries. Maybe there's a workaround.

**Comment by bigsmile01** [comment]
@Maxime-cn  Media Queries don't work for me, so I think it's still an issue.
