### ISSUE TITLE
Make stylebot.me/patterns page more visible in stylebot

### ISSUE THREAD

**Issue by ifmihai** [ankit/stylebot#299]
Please, make http://stylebot.me/patterns more visible
I bumped into it by mistake, not being aware that it exists
The link should be in the description of **Site** field, in creating a new style page

Something like 
"Separate multiple urls with a comma(,) More rules at http://stylebot.me/patterns "

**Comment by irmingard** [comment]
"Site Not Found" ?

**Comment by txdv** [comment]
Yeah, whats with the site not found guys?

**Comment by dreki** [comment]
Please fix this.
