### ISSUE TITLE
Add dialog when user clicks "Remove Styling"

### ISSUE THREAD

**Issue by dredmorbius** [ankit/stylebot#302]
The current browser plugin menu item "Remove Styling" is really bad UI/UX.

If selected, without prompting or confirming, it immediately _deletes_ all styling for a given site.

When hovering (at a risk of deleting the style), it will toggle the style off, but only while hovering over the element, which isn't useful for examining the unstyled version of a large page requiring scrolling (horizontal or vertical).

My suggestion:
- Change the behavior and text from "Remove Styling" to "_Disable_ Styling".  Clicking on this will toggle _state_ but _not_ remove _content_.
- Either put all style deletion controls under the extension Options page, or include the option to delete a style on the Stylebot editor itself.  _INCLUDE A CONFIRMATION DIALOG FOR DELETIONS._

Might also make sense to keep the most recent n deleted styles in a trashcan -- say 10 or so (I rarely delete more than one at any given time).  User state is hard to replace.

**Comment by ankit** [comment]
the enable/disable functionality is now implemented
