### ISSUE TITLE
don't change styles, just save the text raw

### ISSUE THREAD

**Issue by robbiemu** [ankit/stylebot#306]
stylebot changes the order of CSS, most notably @import and @font-face rules will end up in the middle of the document. It destroys the natural order of the document and makes it hard to read. Is there any plan to save the CSS styles as style _documents_ and then on demand load them up and interpret them into style sheets _on demand_? This way we can keep the proper order in the document, as well as comments.

**Comment by Supuhstar** [comment]
+1 every day or so I must edit Stylebot's CSS to put rules in the proper order to work effectively.

For instance, I have one rule that applies to StackOverflow questions and answers. Then, I have a rule that applies to only accepted answers. The way I wrote it, the accepted answer rule applies just fine, but often, Stylebot places it before the more general style, and the accepted answer styles are overridden by what were supposed to be default styles.

**Comment by dredmorbius** [comment]
@Supuhstar I've actually abandoned Stylebot for Stylish, on account of this and other issues.

Dual compatiblity with Firefox among them.

**Comment by Supuhstar** [comment]
@dredmorbius I'm considering moving all my styles to self-hosted CSS files, and just injecting those into webpages instead.

**Comment by ankit** [comment]
stylebot now saves the raw css
