### ISSUE TITLE
Reorganises custom CSS

### ISSUE THREAD

**Issue by Aarilight** [ankit/stylebot#308]
I understand why it does it, but I would appreciate a setting to turn it off. There are issues with it, mainly that on certain elements the css is supposed to be different, overriding previous css, and that doesn't work because it got reorganised to go before it in the page's css.

An example is that I set a bunch of elements to margin: 0; and I wanted to change a single one to margin-left: -8px;
It works fine until I reload the browser and it has reorganised it alphabetically.

**Comment by ankit** [comment]
This is being tracked here: #306
