### ISSUE TITLE
Vulnerability found!

### ISSUE THREAD

**Issue by Asim123** [ankit/stylebot#340]
Hello Sir,
    I found Security Vulnerabilty on http://stylebot.me
SUBJECT:
 Reflected Cross-site scripting(XSS) found on http://stylebot.me.
Bug Information:
1.I find a bug on http://stylebot.me that is Reflected XSS.
2.Its too harmfull.Because through this bug Hackers can able to steal the cookies.
3.Hacker can apply "Stored XSS" on any page.
4.If anyone open that page then he will steal their cookies.Even admin will also steal their cookies.
5.You will further understood after watching attached video.
Fix this bug as quick as possible.
Thanks,
The Security Researcher,
M.Asim Shahzad
![1](https://cloud.githubusercontent.com/assets/5916677/3716080/bd34d956-1600-11e4-8b1a-f5aeb89d255f.jpg)
![2](https://cloud.githubusercontent.com/assets/5916677/3716084/cb0d171e-1600-11e4-9326-ba5e5b72d9ed.jpg)
![3](https://cloud.githubusercontent.com/assets/5916677/3716087/d1558b88-1600-11e4-82c6-2a14ea6d738d.jpg)

**Comment by ankit** [comment]
#352
