### ISSUE TITLE
Pseudo-class :has

### ISSUE THREAD

**Issue by RaulMenaBravo** [ankit/stylebot#349]
I've seen that Stylebot doesn't support the pseudo-class :has 

In my case, I wanted to create a css rule like:
div:has(>div[id*='-ad-']) {display:none}

but it didn't work. The selector is ok because I've tested in Chrome console.

**Comment by ankit** [comment]
Agree with @jordanbtucker, no plans to support jquery selectors. Closing this issue

**Comment by garfieldbanks** [comment]
Since December 2023, this feature works across the latest devices and browser versions:
https://developer.mozilla.org/en-US/docs/Web/CSS/:has
