### ISSUE TITLE
selecting element by shortcut key

### ISSUE THREAD

**Issue by allbetsareoff29** [ankit/stylebot#353]
there needs to be an option to start the element selection process with customizable keyboard shortcut. 
I have a page that utilized  :active  listeners to change css on the fly. I can never select the element I want because:

1) I click on icon (onclick event) which initialized the js behind the scenes to changes the css to display a text field which is normally hidden. This is the field I want to edit with stylebot.
2) I click on "click to enable selection of element" button from stylebot window... which is also onclick event and triggers js behind the scenes.

3) the js behind scenes acts as a toggle. if the field i'm trying to work with is hidden, it will be displayed. If it is displayed, it will be hidden. It is driven off of onclick events. so there is no possible way for me to select this element with your "click to enable selection of element" button. 

Please fix.

**Comment by ankit** [comment]
there is a shortcut already for this, the `s` key
