### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by FKasa** [ankit/stylebot#355]
**This error showed up:**
![image](https://cloud.githubusercontent.com/assets/5333633/5235783/c7e6abee-7812-11e4-991a-812ce6b2ac2e.png)
I have no idea why...
Error text transcribed:

<hr>

> Message: Cannot modify header information - headers already sent by (output started at /home/ankitahuja/stylebot.me/system/application/controllers/user.php:1)
> 
> Filename: libraries/Session.php
> 
> Line Number: 662

<hr>

_UPDATE:_
I just refreshed the page and this showed up:
![image](https://cloud.githubusercontent.com/assets/5333633/5235815/359bdf32-7814-11e4-94ab-c47811929b83.png)
![image](https://cloud.githubusercontent.com/assets/5333633/5235824/913c84a4-7814-11e4-9eef-e2f399faebf7.png)

<hr>

> Message: Cannot modify header information - headers already sent by (output started at >/home/ankitahuja/stylebot.me/system/application/controllers/user.php:1)
> 
> Filename: libraries/Session.php
> 
> Line Number: 662

<hr>

> A PHP Error was encountered
> Severity: Warning
> 
> Message: Cannot modify header information - headers already sent by (output started at /home/ankitahuja/stylebot.me/system/application/controllers/user.php:1)
> 
> Filename: libraries/Session.php
> 
> Line Number: 662

<hr>

> A PHP Error was encountered
> Severity: Warning
> 
> Message: Cannot modify header information - headers already sent by (output started at /home/ankitahuja/stylebot.me/system/application/controllers/user.php:1)
> 
> Filename: helpers/cookie_helper.php
> 
> Line Number: 92

<hr>

**Comment by ankit** [comment]
This is a known issue that happens sporadically every now and then...I need to look into it, thanks for opening the issue
