### ISSUE TITLE
Option to turn on/off global stylesheet

### ISSUE THREAD

**Issue by mationic** [ankit/stylebot#357]
Hi,
I'm using stylebot since a few weeks now. I'm using the global stylesheet as night-mode (darken all sites). What I'm missing is a convinient way to toggle stylesheets on/off. Currently you have to open and click through click through the options to enable the global stylesheet.
There's also just an option to remove stylesheets in the menu. 
Options for quickly disable/enable the global and current active custom stylesheet would be nice.
Adding these entries to the context menu would be a simple solution.. Just as a suggestion..

Keep up the good work!

cheers
mationic

**Comment by ankit** [comment]
Thanks @mationic! Yes, this is an existing open issue #195 Please track this over there, closing this issue!
