### ISSUE TITLE
Stylebot cannot be opened in chrome 40.0.2214.45

### ISSUE THREAD

**Issue by cascer1** [ankit/stylebot#358]
I am unable to open stylebot in any way on Chrome 40.0.2214.45. Clicking it doesn't do anything (No hover effect when I hover over the button either), and right click>stylebot>style * doesn't work either.

**Comment by Nephor** [comment]
I am having same issue

**Comment by HarleyBergo** [comment]
I am having same issue

**Comment by catchmyfame** [comment]
Ditto

**Comment by marcuslindh** [comment]
I am having same issue

**Comment by aljoscha-hark** [comment]
same here, too. aggressively right and left clicking the button made it usable again -- I still dont know the reason. what still does not function is e.g. the "save" button during editing css -- it just flashes back, although the style seems to be saved.

**Comment by poweroftao** [comment]
I have had issues with the behavior of several popups in Chrome lately, e.g. LastPass. Apparently, Chrome has been changing the handling of popups, according to the developer of checker plus for gmail. Please report problems to Chrome via menu button > help > report an issue....

**Comment by jlubeck** [comment]
Same is happening to me on  41.0.2272.118 (64-bit) (OSX)

**Comment by ankit** [comment]
Marking this as a bug. Thanks for reporting
