### ISSUE TITLE
@import url

### ISSUE THREAD

**Issue by superklass** [ankit/stylebot#363]
When I use @import url Stylebot keeps telling me, that a "Syntac Error" occurs.
The same line worked perfectly until yesterday, now it is an error. 

Syntax is:  
@import url("http://www.somedomain.at/css/main.css");

I am using 2.2 , even deleted and installed everything from scratch in Chrome Version 39.0.2171.99 m

**Comment by Concept211** [comment]
I'm getting the same error. what's the deal?

**Comment by ttcg52** [comment]
Me too, not working with this:

@import url(https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic);
