### ISSUE TITLE
Global style for sites with no CSS

### ISSUE THREAD

**Issue by sid-kap** [ankit/stylebot#370]
I often visit websites with no CSS. I want to apply some CSS for these sites specifically. 

(I intend to use a stylesheet similar to [this one](http://bettermotherfuckingwebsite.com/) to improve readability.)

Does anyone else think this would be a useful feature?

**Comment by Orangestar12** [comment]
It already exists in the options.

![Image of Stylebot options, showing Global styles](http://puu.sh/g2I8M.png)

**Comment by sid-kap** [comment]
Is there a way to make this CSS run _only_ on pages with no CSS?

**Comment by Orangestar12** [comment]
Oh I see. I misunderstood you. Sorry about that.

**Comment by ankit** [comment]
@sid-kap No, there isn't a way to apply CSS to *only* websites without CSS. Marking this as a feature request. Thanks
