### ISSUE TITLE
Feedly constantly overwrites my style

### ISSUE THREAD

**Issue by ManOrMonster** [ankit/stylebot#371]
I visit feedly.com daily, and every time my style has been disabled and it's back to the default style. This is the only site I visit that ever does this, and I have no idea how. It happens across multiple machines, so it's definitely the site that is doing it (and it's been going on for a long time).

**Comment by ankit** [comment]
I will debug this, thanks!

**Comment by ManOrMonster** [comment]
Any progress on this? Still have the issue.
