### ISSUE TITLE
Change CSS ID?

### ISSUE THREAD

**Issue by Kirdock** [ankit/stylebot#375]
Is there a way to change the ID of the style tags?
Some Websites are blocking all links where the style id contains "stylebot". (I think that is the problem, I'm not sure)
Is there a way to enter a custom id?

Example:

style type="text/css" id="stylebot-css"
to
style type="text/css" id="myName"

**Comment by ankit** [comment]
Not right now...

That's interesting, can you share which websites are blocking styles containing the id "stylebot"? Thanks

**Comment by Kirdock** [comment]
For example this website
<a href="http://anisearch.com">Anisearch</a>
