### ISSUE TITLE
localhost problems

### ISSUE THREAD

**Issue by muuvmuuv** [ankit/stylebot#377]
Hey,

I want to overwrite my localhost/ dir but just the localhost/webseiten/ and one dir under cause after my pages coming with content that i dont want to ow.. so how can i fix this, I tried regex at all...?

Regards and thanks
Muuvmuuv

**Comment by ankit** [comment]
I am not sure i understand what you mean, can you be a bit more specific?

**Comment by muuvmuuv** [comment]
mhm i mean, that i can say that my style will just shown in this " localhost/webseiten/* " for example: "localhost/Webseiten/work"
"localhost/webseiten/"
But not In the dir under "work" - "localhost/webseiten/work/project1" !

My Filetree looks like this:
localhost/webseiten
localhost/webseiten/work
localhost/webseiten/mysite
localhost/webseiten/work/project1

**Comment by muuvmuuv** [comment]
Did anyone has an answer?

**Comment by muuvmuuv** [comment]
@ankit maybe you now know an answer for me. Im still in trouble and really want to use a stil for this space of sites.

**Comment by muuvmuuv** [comment]
Lmao, I wrote that? Omg haha, I do not know what I was trying back then but I had to be drunk. 🤣

**Comment by ankit** [comment]
hehe :)
