### ISSUE TITLE
Stylebot loading in jQuery and breaking some sites

### ISSUE THREAD

**Issue by aaronharding** [ankit/stylebot#383]
Hey,

I came across this error the other day where some sites were breaking and have pinned it down to my stylebot extension. Disabling only the stylebot extension causes the sites to run fine. I'm not sure what is happening exactly, but first the console reads that an element cannot be reached and then jQuery/$ is not defined:

```
Uncaught TypeError: Cannot read property 'opacity' of null(anonymous function) @ jquery.js:2(anonymous function) @ jquery.js:2(anonymous function) @ jquery.js:4
colorpicker.js:397 Uncaught ReferenceError: jQuery is not defined(anonymous function) @ colorpicker.js:397
jquery.tipsy.js:216 Uncaught ReferenceError: jQuery is not defined(anonymous function) @ jquery.tipsy.js:216
selectize.js:9 Uncaught ReferenceError: jQuery is not definedregex @ selectize.js:9(anonymous function) @ selectize.js:11
init.js:4 Uncaught ReferenceError: $ is not defined(anonymous function) @ init.js:4
jquery.js:2 Uncaught TypeError: Cannot read property 'opacity' of null(anonymous function) @ jquery.js:2(anonymous function) @ jquery.js:2(anonymous function) @ jquery.js:4
colorpicker.js:397 Uncaught ReferenceError: jQuery is not defined(anonymous function) @ colorpicker.js:397
jquery.tipsy.js:216 Uncaught ReferenceError: jQuery is not defined(anonymous function) @ jquery.tipsy.js:216
selectize.js:9 Uncaught ReferenceError: jQuery is not definedregex @ selectize.js:9(anonymous function) @ selectize.js:11
init.js:4 Uncaught ReferenceError: $ is not defined
```

![screen-shot-2015-05-08-at-15 12 26](https://cloud.githubusercontent.com/assets/1704000/7536955/17e50a6e-f595-11e4-8e30-8cec5d8e230c.png)

You can see the extension ID in the right hand side which led me to Stylebot.

Any ideas on what to do?

(perhaps this isn't Stylebot related, and the websites causing the conflict, but still I thought I would let you know)

Best,

**Comment by jrodl3r** [comment]
:+1:

**Comment by ankit** [comment]
Thanks for reporting the bug! @aaronharding and @jrodl3r, can you give example sites where stylebot breaks this way? Thanks

**Comment by ScheintodX** [comment]
you just have to embed an svg with an object tag like <object data="someimage.svg"></object> in order to get those errors

**Comment by aaronharding** [comment]
hey ankit, sorry for not replying sooner than.. well almost a whole year. I will try and get around to recreating the issue again. Perhaps @ScheintodX is right. When I next have a chance I'll try it with @ScheintodX's instructions.
