### ISSUE TITLE
Idea: Load a stylesheet from the filesystem

### ISSUE THREAD

**Issue by architectcodes** [ankit/stylebot#387]
Hi,

I have a theme I want to manage with version control. At the moment I just copy the styles back and forth, and push the changes to the social site every now and then. That’s a lot manual labor, and can cause issues.

It would be great if I could specify a file on the filesystem from which stylebot would pull a stylesheet. It would be even greater if stylebot could write to this file as well when I change the stylesheet.

I hope it’s possible whatsoever :)

**Comment by ankit** [comment]
I will mark this as a feature request. Ideally, it would make sense to have integration with Github or some versioning system.

**Comment by tomekwi** [comment]
:+1: Wow, that would be great!
