### ISSUE TITLE
Love this app, being using it for over a year. But...

### ISSUE THREAD

**Issue by mrobinson537** [ankit/stylebot#388]
Seems to have stopped working recently. Though all my custom stylesheets are enabled, they are not being loaded. And I can no longer edit them in the stylebot options. Clicking the edit button doesn't seem to do anything.

**Comment by ankit** [comment]
Thanks @Matterful, can you add your OS version and Chrome browser version here. Thanks

**Comment by GLolol** [comment]
I think I'm getting a similar issue here: I newly installed Stylebot, but the "Open Stylebot" and right click "Style Elements" options don't do anything at all.

Running Chrome 43.0.2357.130 m on Windows 7.

**Comment by Matterful** [comment]
Sorry about that, I should've been more specific. I'm on OS X Yosemite version 10.10.3, runnning Chrome 43.0.2357.130 (64-bit).

**Comment by Matterful** [comment]
Hopefully this helps a bit more. Here is the error messaging from my console, when on the stylebot options page.

Uncaught TypeError: Cannot read property '_enabled' of null      -----  @ace.js:101 
Missing module: 
   Reactlookup @ ace.js:101 
   window.require @ ace.js:83(
   anonymous function) @ VM146:49
   (anonymous function) @ VM146:256
   InjectedScript._evaluateOn @ VM143:895
   InjectedScript._evaluateAndWrap @ VM143:828
   InjectedScript.evaluate @ VM143:694
Missing module: react   --- @ace.js:101

**Comment by gittyhub911** [comment]
I can confirm Matterful, having the same issue. Everything was working fine yesterday but today it doesn't want to play ball.

"Uncaught TypeError: Cannot read property '_enabled' of null"
