### ISSUE TITLE
How can make it run in other chrome extension

### ISSUE THREAD

**Issue by theduyet** [ankit/stylebot#389]
Hi,
It run very well in normal mode of chrome.
But i am using other extension of chrome https://chrome.google.com/webstore/detail/the-economist/gebjgjhbjedcomcajgpodjgfjgkepgpl?hl=en-GB, stylebox doesnot working. 

I have check this extension, it always load the website app.economist.com and in this page, they have  default css which doesn't allow us to select text.
I mean how  can stylebox run in this extension?

**Comment by rchkb** [comment]
I'm not sure if this is possible; the app spawns an entirely separate instance of Chrome.

**Comment by ankit** [comment]
+1 to what @rchkb said. I don't this think Chrome supports running extensions inside apps.
