### ISSUE TITLE
Is it possible to use Stylebot to modify the CSS stylesheets of other Chrome Extensions?

### ISSUE THREAD

**Issue by MeoMix** [ankit/stylebot#390]
Hey,

I would like to use Stylebot to modify another extension.

I tried adding a new style with the URL pattern "chrome-extension://jbnkffmindojffecdhbbmekbmkkfpmjd". It did not appear to take effect.

Is it possible to do this?

**Comment by ankit** [comment]
Last I checked, there wasn't a way to do this.
