### ISSUE TITLE
Css google font showing only on half of the page, needs CSS hack

### ISSUE THREAD

**Issue by zhgabor** [ankit/stylebot#391]
i found out the this plugin is causing the chrome font bug to kick in ... when i disable the plugin everything looks fine.
![bug-font](https://cloud.githubusercontent.com/assets/12900744/8497091/ec03bebc-2182-11e5-9996-96ab388bb8c5.PNG)

it should look like:
![bug-font-ok](https://cloud.githubusercontent.com/assets/12900744/8497104/0e7b4456-2183-11e5-93a9-bf84eece961c.PNG)

**Comment by ankit** [comment]
Can you please share the URL, thanks!

**Comment by zhgabor** [comment]
its not doing that anymore... i just re-enabled the stylebot extension it looks ok now.
the url is: [anemoneart.ro](http://anemoneart.ro)
