### ISSUE TITLE
If opened tabs from other extensions, it does not apply CSS by stylebot.

### ISSUE THREAD

**Issue by quantumleap-** [ankit/stylebot#394]
For example, it opened from the extension <a href=https://chrome.google.com/webstore/detail/better-history/obciceimmggglbmelaidpjlmodcebijb?utm_source=chrome-app-launcher-info-dialog>"Better History"</a>.
(Other "history-related extension" even confirmed the same malfunction.)

malfunction
· Styebot css(not apply)

· Styebot context menu
· Styebot menu in the toolbar button
...Therefore it can not be opened css editor.

//This is due to the specifications of chrome?(or stylebot?)

**Comment by ankit** [comment]
Styling chrome:// tabs belonging to other extensions is not supported.
