### ISSUE TITLE
stylebot do not support class names with a dot in them

### ISSUE THREAD

**Issue by JonasNo** [ankit/stylebot#396]
eg class="foo.bar"

What I have tried:

```
.foo.bar {
    color: blue;
}

.foo\.bar {
    color: blue;
}

.foo\\.bar {
    color: blue;
}
```

document.getElementsByClassName do support this.
Simply using:

```
document.getElementsByClassName('foo.bar');
```

For now I have been forced to write a userscript to do the job.

**Comment by victordarras** [comment]
Hi, you can use this selector :
~~~css
[class="foo.bar"]
~~~

**Comment by JonasNo** [comment]
I appreciate the suggestion. Thank you.
