### ISSUE TITLE
Need a way to temporarily disable style

### ISSUE THREAD

**Issue by Crias** [ankit/stylebot#397]
My primary use of StyleBot is to show a nice big banner that says "DEVELOPMENT" or "PRODUCTION" when working on website software for work. In the past I've come very close to making some very bad mistakes by being on the wrong environment...

Because the styling also gets applied to iFrames, and we use iFrames in order to display modals, it often makes it difficult to see exactly how those modals are styled. I also need the banner to not display when I'm doing a demo to stakeholders - they often get confused, thinking the actual product will display the banner.

Currently, if I mouse over the "remove style" button it temporarily hides the styles, but then I can't interact with the page. If I click "remove style" it deletes the style - I've already had to recreate my banner CSS once because I accidentally lost it this way.

I would like a button in the StyleBot drop-down to temporarily disable a particular style. Clicking again would toggle it back on.

Thanks very much :) this extension is awesome.

**Comment by ankit** [comment]
Thanks @Crias. This is an existing feature request, please track it here: #195 (closing this issue)
