### ISSUE TITLE
Can't open stylebot on https://webwinha.metropolia.fi/

### ISSUE THREAD

**Issue by omidfi** [ankit/stylebot#398]
I just got to know this nice plugin! However I can't open the style bot on a certain website after I login
https://webwinha.metropolia.fi/

Is it part of the known problems that it just doesn't work on some websites?

**Comment by valespring** [comment]
Works for me - not sure what's up with your end.

**Comment by ankit** [comment]
+1, If i go to that URL, it works for me.
