### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by Supuhstar** [ankit/stylebot#403]
I have CSS for many sites set up. On last Friday, they worked perfectly. When I came back to work today, they no longer work. I restarted Chrome and it had no impact. Site names are a mix of basic and regex strings.

The CSS still shows up in the options page, but not on the pages I'm styling.

![www.Google.com with no custom styles applied](https://cloud.githubusercontent.com/assets/1350020/9741215/2f84236a-5627-11e5-8e3b-e5c7c711d52c.png)
![Stylebot options showing custom CSS for www.Google.com](https://cloud.githubusercontent.com/assets/1350020/9741214/2f8415e6-5627-11e5-86cb-e7c37a4d4c9c.png)

**Comment by marlun** [comment]
Are you on Google Chrome Carnary? It stopped working for me too because of this error:

    chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/background/styles.js:106 Uncaught TypeError: Cannot read property '_enabled' of null

**Comment by Supuhstar** [comment]
@marlun No, I'm on my workstation where I don't do betas. On my personal computers, ironically, I don't use Stylebot nearly as much.

Also no, my console is empty. **Strangely, adding the same styles again works just fine, so that's my current workaround.**

**Comment by JoshHelfferich** [comment]
Same here, Stylebot just flat-out stopped working on Chrome OS X 45.0.2454.85 (64-bit)

**Comment by marlun** [comment]
I couldn't even export my styles to move it to my stable version.

**Comment by cyrylski** [comment]
I have the same issue. Probably related to a pending update. Stopped working before Chrome 45.0.2454.85 m 64bit.

**Comment by Avallach7** [comment]
The same problem. Options page doesn't work properly because of NRE mentioned by Marlun. I cannot view nor export my styles too. There is some transformed css code in Chrome storage, but it contains all "revisions" of my styles, what makes finding correct ones nearly impossible.

Some external exporter would be *very* helpful.

**Comment by Supuhstar** [comment]
@Avallach7 Perhaps using a merge tool will help you.

On Tue, Sep 22, 2015 at 5:07 PM Avallach7 <notifications@github.com> wrote:

> The same problem. Options page doesn't work properly because of NRE
> mentioned by Marlun. I cannot view nor export my styles too. There is some
> transformed css code in Chrome storage, but it contains all "revisions" of
> my styles, what makes finding correct ones nearly impossible.
>
> Some external exporter would be *very* helpful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ankit/stylebot/issues/403#issuecomment-142422437>.
>
-- 
— Kyli Rouge —

**Comment by Avallach7** [comment]
What exactly tool do you mean? 
To elaborate, there was a file %localappdata%\Google\Chrome\User Data\Default\Local Extension Settings\oiaejidbmkiecgbjeifoejpgmdaleoha\000003.log which contained JSON with transformed css styles, e.g. "body":{"background":"red"}. I was able to transform them again into css with regular expressions, but still don't know how to find most recent style for every page from dozens saved by extension, probably one every time I have changed something. I do not need to merge them - they are not saved incrementally, but separately, and older versions contain things I do not want. I can make diffs andy try to remember which was introduced later, but this is lot of work. By external exporter I mean tool that would take whole 000003.log and output set of css files, one for every style I created.
I know that I should have created backups before, but I realized that such option exsists after it ceased to work.

**Comment by Supuhstar** [comment]
Oh, I see what you mean. I thought you meant you found diff files.

I'm currently in the process of moving my styles to self-hosted CSS.

On Wed, Sep 23, 2015 at 2:22 AM Avallach7 <notifications@github.com> wrote:

> What exactly tool do you mean?
> To elaborate, there was a file %localappdata%\Google\Chrome\User
> Data\Default\Local Extension
> Settings\oiaejidbmkiecgbjeifoejpgmdaleoha\000003.log which contained JSON
> with transformed css styles, e.g. "body":{"background":"red"}. I was able
> to transform them again into css with regular expressions, but still don't
> know how to find most recent style for every page from dozens saved by
> extension, probably one every time I have changed something. I do not need
> to merge them - they are not saved incrementally, but separately, and older
> versions contain things I do not want. I can make diffs andy try to
> remember which was introduced later, but this is lot of work. By external
> exporter I mean tool that would take whole 000003.log and output set of css
> files, one for every style I created.
> I know that I should have created backups before, but I realized that such
> option exsists after it ceased to work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ankit/stylebot/issues/403#issuecomment-142506675>.
>
-- 
— Kyli Rouge —

**Comment by david-mark** [comment]
Yep. It's dead. :(

Script throws an exception in options and no styles applied at this point. Can't export either due to the error. Stylish, somebody said?

**Comment by Supuhstar** [comment]
Yep, I moved all my styles to GitHub and just put @import sheets into
Stylish. It wasn't easy, extracting them from StyleBot, but it was worth it.

On Mon, Nov 16, 2015 at 8:27 PM David Mark <notifications@github.com> wrote:

> Yep. It's dead. :(
>
> Script throws an exception in options and no styles applied at this point.
> Can't export either due to the error. Stylish, somebody said?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ankit/stylebot/issues/403#issuecomment-157230805>.
>
-- 
— Kyli Rouge —
