### ISSUE TITLE
Stylebot lost all my style rules and no longer saves new ones

### ISSUE THREAD

**Issue by iamfantastikate** [ankit/stylebot#410]
Not sure if this is a fluke or not, but I thought I better report it. I restarted Chrome today for an upgrade (to Version 46.0.2490.80 m), and Stylebot promptly lost ALL my rules. None of my other extensions did anything odd. 

This is heartbreaking. I'm seeing YouTube comments and celebrity news on Facebook. It's fixable, of course, but...boy, am I sad that I have to redo everything. I've used Stylebot for about three years now without issue. 

EDIT: It no longer saves new rules, either. Any rules I give it on a page will work, but they aren't saved when I leave the page. If it helps to know, I only use the advanced editor.

**Comment by ankit** [comment]
Hi @iamfantastikate I am really sorry you lost your styles. I have been meaning to fix stuff in Stylebot but cannot make any time :(

I will take a look at this specific issue as soon as i get a chance. Meanwhile I recommend using `stylebot.me` to back up your styles.

**Comment by C99nl** [comment]
The same here, I lost all my 60+ styles!!
I have to re-style everything again...

**Comment by iamfantastikate** [comment]
@C99nl I'm not sure you should bother. :( Stylebot won't save them anymore, period. It'll work while you're on the site, but as soon as you leave, the extension resets and loses the information again.

Hope you're able to look at this at some point, @ankit! I so appreciate the work you put into the original extension and will be very happy if you get around to fixing it!

**Comment by C99nl** [comment]
Ah damn, you're right...
Once you leave the site, it resets everything.
Please fix this as soon as possible.

**Comment by amitgupta-work** [comment]
Same issue here. I can see list of styles in options. But It is not letting me modify them. And showing the count 0 of total styles. I don't even have the backup. I afraid to create all of them again.

**Comment by C99nl** [comment]
Please, when will this be fixed?
I'm waiting for 1 month already...

**Comment by iamfantastikate** [comment]
Switch to Stylish, everyone. It's not as elegant, but it works.

**Comment by ElectricSwan** [comment]
I had the same problem, but luckily I had previously exported my styles, so I only lost a few recently added sites. I found that uninstalling and reinstalling Stylebot seems to fix the problem. After reinstalling, I imported my previously exported styles, and Stylebot still worked on those sites even after rebooting Chrome (Version 47.0.2526.106 m).

**Comment by alphatonic** [comment]
I just edit the CSS with stylebot and then transfer it to stylish.

**Comment by C99nl** [comment]
@alphatonic If you re-install StyleBot, it'll work again.
Kinda sad to see the owner not caring about this.
