### ISSUE TITLE
Google Web Fonts (As described in #231) no longer work

### ISSUE THREAD

**Issue by jm3** [ankit/stylebot#423]
contrary to #231, Google Web Fonts do not appear to work anymore.

10 second repro screencast: https://www.dropbox.com/s/16sg024bgvfqh68/stylebot-google-fonts-github-bug-report.mp4?dl=0

the screencast shows Lato working (because I have the font natively installed on my Mac), but Roboto and Monserrat not working — they display as Times New Roman.

**Comment by raajtram** [comment]
@jm3 Google fonts have been removed from the list of fonts.
