### ISSUE TITLE
Remove Styling is a hidden nuke

### ISSUE THREAD

**Issue by stegrams** [ankit/stylebot#426]
I just selected "Remove Styling" from extensions bar menu in Chromium and, with no warnings, Stylebot deleted all the styling from a page I had made.

I expected this menu option to turn in to "Add Styling" or something.
Is it possible to recover my work?

If not, I think it would be better to have at least a warning on this destructive option.

**Comment by ankit** [comment]
sorry about that @stegrams :( I will try and fix this issue soon. Closing this as a duplicate of #337

**Comment by stegrams** [comment]
Anyway except that, Stylebot is an excellent project. Thanks for sharing.
