### ISSUE TITLE
Hides when body is hidden

### ISSUE THREAD

**Issue by Booligoosh** [ankit/stylebot#431]
I was trying to change a website, and to make the body hidden using `display: none`. Of course, the stylebot editor is part of the body, so it dissapeared. In the end I had to get it back with inspect element, and turn live preview off so I could finish editing. Could there be some kind of automatic override so that it would hide everything **except** the editor?

**Comment by raajtram** [comment]
@Booligoosh - can you wrap everything inside <body> into a different container, and then hide that container instead of hiding the <body>?

**Comment by Booligoosh** [comment]
@raajtram but stylebot can only edit css, right?

**Comment by raajtram** [comment]
@Booligoosh - ah, my bad - I thought you were working on your own website. Nevertheless, unless that website is poorly built, you can hide the few main containers on that site to effectively hide everything.

**Comment by Booligoosh** [comment]
@raajtram that would work, but unfortunately not all websites are built like that (I wish they were)
