### ISSUE TITLE
Why does Stylebot not work on chrome:// addresses?

### ISSUE THREAD

**Issue by AlexJohn73** [ankit/stylebot#447]
Not sure whether this has been asked before, but I am trying to customise some chrome:// addresses. Sometimes, Stylebot will open the CSS editor, and I am able to make changes easily, but in most cases the editor can't be opened to edit the page. Is there restrictions on this? Because if there are, the aren't working very well...
Any response is much appreciated!

**Comment by speeditor** [comment]
I'm not sure Chrome extensions can access internal browser pages - probably for security reasons.

**Comment by geckoseo** [comment]
The chrome:// addresses are not actually real uri, they are shortcuts to settings in the browser itself, and as such are not possible to be accessed by extensions. The addresses serve as redirection to the settings options in other words.

It would be a huge security risk if an extension could alter the content of the DOM elements of the browser locally.

While it would probably be possible to write an extension to hack this, the extension would need to be downloaded and installed by the owner of the machine on which Chrome is installed. Such an extension would never meet the Chrome Store criteria for acceptance, and the only place one might find such a thing to download would in "the wild". Basically it would be like deliberately downloading a trojan, so if you want to do something like this for personal use, you would need to code it yourself.

**Comment by ankit** [comment]
yes, afaik, chrome doesn't allow running content scripts on chrome:// urls
