### ISSUE TITLE
!important is removed

### ISSUE THREAD

**Issue by jmckib** [ankit/stylebot#45]
If I click Edit CSS, then add a rule like
p {
color: red !important;
}
and click Save, the !important will be removed next time I open Edit CSS on that page.

**Comment by Signy13** [comment]
But still - why it is the !important removed? 
The fact that Stylebot add it later should not mean that Stylebot can remove it from my code. 
I use the same CSS on more places (not only in Stylebot) and it is problem when Stylebot changes my code.
I would appreciate when Stylebot left my CSS code intact and internally append !important to those parts where it is missing.
