### ISSUE TITLE
Stylebot forgets rule order on restart

### ISSUE THREAD

**Issue by viridium** [ankit/stylebot#452]
After a browser restart, Stylebot reorders my manually entered styles. As a consequence, the styles don't apply properly.

These styles:

```
@import url(https://fonts.googleapis.com/css?family=Droid+Sans:400,700);
:not(.monofont) { font-family: 'Droid Sans'; }
.monofont * { font-family: 'Source Code Pro'; }
```

Come up reordered like this:

```
.monofont * { font-family: 'Source Code Pro'; }
:not(.monofont) { font-family: 'Droid Sans'; }
@import url(https://fonts.googleapis.com/css?family=Droid+Sans:400,700);
```

As part of the CSS standard, rule ordering matters. How can such an obvious bug sneak through for so long?

**Comment by viridium** [comment]
Is this bug report even visible to anyone?

**Comment by Icebird** [comment]
This is a problem for me as well.

**Comment by AnEmortalKid** [comment]
@viridium you're welcome to try to fix it via a PR

**Comment by silverdragon686** [comment]
Any word on this bug getting fixed? Causing issues on my end.

**Comment by AnEmortalKid** [comment]
You can submit a PR with a fix if you feel like it @silverfragon686

**Comment by silverdragon686** [comment]
No idea how to do that, otherwise I would. I'm assuming the previous person didn't either, otherwise the bug would have been addressed by now.

**Comment by AnEmortalKid** [comment]
Yup. I haven't had time to look at it, been busy with another OS project

**Comment by Icebird** [comment]
I found a fix, but haven't had time to solidify it and  submit a PR.

If I remember right, basically you just need to json.stringify before you
save to browser storage instead of storing the css object directly.


-Konrad

**Comment by Icebird** [comment]
Fixed this issue in [Pull request 478](https://github.com/ankit/stylebot/pull/478).
