### ISSUE TITLE
Using stylebot to read an article on one page?

### ISSUE THREAD

**Issue by orschiro** [ankit/stylebot#453]
Dear @ankit,

Thanks for stylebot!

Can it be used to read the [Blinkist Daily](https://app.blinkist.com/en/daily/reader/playing-the-whore-en/) on one page instead of having it split across several pages?

Thanks!

**Comment by AnEmortalKid** [comment]
Looks like you could overwrite chapter with what chapter_visible has, or set:
"display:block; opacity:1" on everything.

**Comment by orschiro** [comment]
Dear @AnEmortalKid,

This is it, thank you! :-)
