### ISSUE TITLE
Variables / Custom Properties

### ISSUE THREAD

**Issue by ghost** [ankit/stylebot#454]
the relatively new CSS standard for custom properties is not supported. 
example:
--myvariable: "a string";

if you click save, and go back to edit it, that line will have been automatically removed from the CSS script.

by looking in the parser, it appears there's some type of support (it looks for var(), which is how you access myvariable later), but i'm not sure what its expecting the declaration to look like, I just know its not the double-dash.

**Comment by bsmith-cycorp** [comment]
I would take this a step further and request that the parser doesn't modify the stylesheets at all on save. That way if there's a new CSS feature, you don't have to add support for it to allow its use.

**Comment by Olrios** [comment]
Just use
`\-\-`
instead of
`--`
