### ISSUE TITLE
Add ability to use local fonts

### ISSUE THREAD

**Issue by Hadi290** [ankit/stylebot#456]
There are some extensions with this kind of features like "Font Changer with Google Web Fonts™" which allows to upload .ttf files and use them, but those extensions change the font-family for entire page and cause error for sites that are using fonts like font-awesome for their images.
Please integrate this feature in Stylebot so we can use local fonts for specific elements.

**Comment by cbetancourt** [comment]
You can achieve the same results by installing SkyFonts on your computer, using it to install your favorite fonts from Google Fonts, and then referring to them in your Stylebot CSS.

An added bonus is that SkyFonts only needs to run when adding or removing fonts.
