### ISSUE TITLE
Any way to redefine inline !important

### ISSUE THREAD

**Issue by vvscode** [ankit/stylebot#457]
I'm trying to solve redefinition for inline `!important` style. But didn't find any option.  In old versions on Opera it was able. Is there some tricks?

I use http://output.jsbin.com/gerasewuso for tests

**Comment by JonasNo** [comment]
Inline styles set with `!important` takes precedence. The only way I've found to make stylebot css to work is with a userscript that removes the `!important` or the whole inline style from all or specific elements depending on site structure.

Stylebot could have added a feature to do this automatically but it haven't yet, unfortunately.
