### ISSUE TITLE
How to modify chat window on Twitch?

### ISSUE THREAD

**Issue by XxBonf1r3xX** [ankit/stylebot#458]
1.

I would love to have a Stylish script to make chat wider horizontally on Twitch, Twitch used to have a "drag" option to make it wider but looks like they removed it.

2.

I would love to have Stylish script to make chat text entering area wider vertically, the box where you type your text in chat is too small in my honest opinion.

**Comment by AnEmortalKid** [comment]
Grab the class names and make custom css setting the width to like 150%?
