### ISSUE TITLE
Feature request: show URL pattern when move a cursor on "patterns" link

### ISSUE THREAD

**Issue by kubosho** [ankit/stylebot#459]
<img width="870" alt="2017-01-20 1 05 28" src="https://cloud.githubusercontent.com/assets/430267/22114423/bf37aa22-deac-11e6-8f6e-3127b2e7d320.png">

## Current behavior

Show URL patterns on new tab when click "patterns" link.

## Want this behavior

Show URL patterns when move a cursor on "patterns" link.

**Comment by kubosho** [comment]
I will development this feature, and will send Pull Request.

**Comment by GavBurke** [comment]
Also, http://stylebot.me/patterns is giving error of:

A Database Error Occurred
Unable to connect to your database server using the provided settings.

**Comment by joelamos** [comment]
What pattern can I employ to only match the base URL? I currently have no way of knowing how the patterns work.
