### ISSUE TITLE
stylebot.me is down

### ISSUE THREAD

**Issue by TheJaredWilcurt** [ankit/stylebot#462]
> **A Database Error Occurred**
> Unable to connect to your database server using the provided settings.

<p align="center"><img alt="Screenshot of above message" src="https://cloud.githubusercontent.com/assets/4629794/22931150/8fe08a84-f291-11e6-8522-9421be2a188c.png"></p>

**Comment by ankit** [comment]
@TheJaredWilcurt Thanks for reporting, I will put up a maintenance page soon as I work on updating the site

**Comment by darkufo** [comment]
Any update to when this will be working again.

**Comment by ManOrMonster** [comment]
Is this going to get fixed? The issue that I mentioned before about feedly.com somehow making Stylebot drop the style every time means that the only way I can get my style back (that I've tweaked over several years) is to log into stylebot.me.

**Comment by ankit** [comment]
Hello everyone. I do plan to bring stylebot.me back up soon. With my day job, it's hard for me to find time to do this, but i will do it. 

Please keep track of this issue here: https://github.com/ankit/stylebot/issues/466. Closing this as a duplicate

**Comment by ManOrMonster** [comment]
Thanks for the update.
