### ISSUE TITLE
Create option to edit styles not on domain, but also pages

### ISSUE THREAD

**Issue by seansan** [ankit/stylebot#465]
Create option to edit styles not on domain, but also pages

We work on editing different pages using CSS

So a global sheets/edit screen is not always the solution

Would be great to edit per page or per route

**Comment by elbuenob** [comment]
I'd like this feature as well - it could be super useful!

**Comment by elbuenob** [comment]
Actually this feature already exists:

Stylebot Options > Styles > Add a new style… > URL

Add your URL and add your styles. Très bien!

**Comment by ankit** [comment]
yes, you can do this via the options page but not via the editor yet
