### ISSUE TITLE
Database error occured.

### ISSUE THREAD

**Issue by laurentvaills** [ankit/stylebot#466]
I get the message 

>A Database Error Occurred
> Unable to connect to your database server using the provided settings. 

when I try to connect to http://stylebot.me/ .

**Comment by etuan** [comment]
+1

**Comment by adymitruk** [comment]
+1

**Comment by dmakhno** [comment]
+1

**Comment by efimov90** [comment]
+1 very long time

**Comment by andras-gyarmati** [comment]
+1, I'm very sad. Can I help somehow?

**Comment by ankit** [comment]
Hello everyone. Yes, this is a known issue and I am planning to bring stylebot.me back up soon. Unfortunately, I have very little time after my day job but I do plan to bring the site back up.

**Comment by TheJaredWilcurt** [comment]
:+1:

**Comment by kzu** [comment]
In the meantime, I'm using wayback to learn about patterns: https://web.archive.org/web/20160304162602/http://stylebot.me/patterns

**Comment by IGitSylvia** [comment]
x2

**Comment by XelaNimed** [comment]
In my opinion, the project has died. No support, updates or improvements. Maybe it makes sense to create a new project based on this?

**Comment by seanfuture** [comment]
@ankit is the website open source?  I'd consider allowing the community to assist

**Comment by Phrogz** [comment]
I'd really love to extract the styles that I've added. Is there a copy of the database available that we could download and search manually?

**Comment by ManOrMonster** [comment]
You can search archive.org and find your profile page from last year to find your styles you've uploaded.

**Comment by Phrogz** [comment]
> @ManOrMonster wrote: _"You can search archive.org and find your profile page from last year to find your styles you've uploaded."_

Sadly, archive.org does not appear to have my profile page cached.

**Comment by ManOrMonster** [comment]
Is your profile name phrogz on stylebot?

**Comment by Phrogz** [comment]
@ManOrMonster Good question. I don't know. The likely candidates are `phrogz`, `phrogz42`, `gkistner`, and `gavinkistner`. Either the Wayback Machine doesn't have those cached, or I'm failing to enter the proper URL.

**Comment by ManOrMonster** [comment]
@Phrogz Looks like you may be out of luck. Unfortunately, my latest archive was from 2015, so the only one I needed to recover was out-of-date anyway.

**Comment by c01000100** [comment]
bump

**Comment by matthewryanparker** [comment]
@ankit , I know you're busy and this probably isn't the most financially successful adventure with limited financial incentive. But I would love it if you (or I or community) got the webpage back up and running. I would also love to port this extension to Firefox. I prefer this extension to Stylish because I can actually use the hand picker and select elements. Anyway, thank you for your contribution to this! This extension has completely changed my power browsing experience.

**Comment by rhavens** [comment]
I'd love to help with whatever you need to get this up and running again. I know this is open source and I could easily make a clone, but considering the size of the community it'd be great to get it started again from its roots. This tool is exactly what I need and it'd be great if I could share styles easily.

**Comment by liloli** [comment]
I love this one, could find another one like this. It'll be great if you guys can bring it back alive.

**Comment by killgo** [comment]
Man 
WE ARE ALL WAITING!

**Comment by matthewryanparker** [comment]
Can we please get this project back on its feet again? I love this extension and would love to be able to have the website back that shared user submitted styles. It was cool to visit a website and see if a style has been made for it by someone.

**Comment by killgo** [comment]
At least author please make it open source so we could do it by ourselves!))) Thanks!

**Comment by ManOrMonster** [comment]
I would recommend switching to [Stylish](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en). This project seems to be dead.

**Comment by killgo** [comment]
@ManOrMonster thanks!

**Comment by dunnojo** [comment]
Please don't use Stylish unless you want to get tracked.
Here's a quote from the Stylish wikipedia article.

> As of 2017, it is owned by SimilarWeb, a market intelligence company that tracks at least 8 million users through browser extensions and other tools.

I'd recommend the Stylus extension which is a fork of Stylish but without the user tracking.
Stylus also supports userstyles from userstyles.org

**Comment by ankit** [comment]
i am re-writing the extension to v3 and will follow up with a new website.
