### ISSUE TITLE
unable to open stylebot

### ISSUE THREAD

**Issue by flojnel** [ankit/stylebot#471]
Stylebot won't open in Chrome Version 57.0.2987.133 (64-bit). I can open options, but not the CSS editing window (my favorite tool!).

**Comment by GREATMAN77** [comment]
I DON'T KNOW WHAT TO DO.  . ALL MY  TRANSACTIONS IN THE NET ARE STOPPED. PLEASE HELP ME NOW.

**Comment by GREATMAN77** [comment]
OK, HOW THEN DO I OPEN MY SYSTEM TO CONTINUE MY MANY  MATTER WAITING FOR MY ATTENTION?.
