### ISSUE TITLE
Dreamhost issues?

### ISSUE THREAD

**Issue by yellowjaguar5** [ankit/stylebot#477]
Hello @ankit!
I love the premise of this plugin, but when I navigated to [stylebot.me](http://stylebot.me), I got the following screenshot. I thought people here should know.
Thanks!
![screen shot 2017-06-15 at 9 06 05 pm](https://user-images.githubusercontent.com/15172054/27211522-ac99f4e4-520e-11e7-954a-01850bb026c3.png)

**Comment by AlexByte** [comment]
Site is finally died https://github.com/ankit/stylebot/issues/466

**Comment by yellowjaguar5** [comment]
Thanks @AlexByte. That's too bad.

**Comment by AlexByte** [comment]
Just use Stylish

**Comment by etuan** [comment]
I have a theme that I put a bunch of work into, that I only stored here. Is there any chance you have that somewhere in your dreamhost database and I can get it?

**Comment by MonicaUnlimited** [comment]
good grief :-(

**Comment by MonicaUnlimited** [comment]
does anyone know why the message when adding to Chrome "can read and change your bookmarks" ??

**Comment by Fonger** [comment]
If all you want is patterns document, here you go.

# Stylebot Patterns
## Basic (default)
By default, Stylebot uses simple text strings to match styles to websites. Examples:
 - `docs.google.com` : Matches any URL with `docs.google.com` in it.
 - `docs.google.com, spreadsheets.google.com` : Matches any URL with `docs.google.com` or `spreadsheets.google.com` in it.

## Advanced
Stylebot supports wildcards `**`, `*` and `,`

 - `**` matches any character sequence. Examples:
   - `docs**`: Any URL beginning with `docs`.
 - `*` matches any character sequence, until a `/` is found.
   - `docs*.google.com`: This will match `http://docs.google.com`, `http://docs1.google.com`, `http://docs2.google.com` and so on.
   - `*.ycombinator.com`: This will match `http://news.ycombinator.com` and `http://apps.ycombinator.com`
 - `,` separates a list of advanced patterns. Matches a URL if any sub-pattern matches it.

## Regular Expressions
Stylebot treats a string as a regex if it start it with `^`. Examples:
`^http://www.reddit.com/$`: This matches only the Reddit homepage.

**Comment by ankit** [comment]
sorry for the lack of response everyone. the website is down currently and i plan to bring it back up in the future.
