### ISSUE TITLE
conditional

### ISSUE THREAD

**Issue by kofifus** [ankit/stylebot#479]
I am using stylebot to turn white background to offwhite to save my eyes

I added a global stylesheet:
```
body {
    background: #F1F1F1;
}

```

Is there a way for me to say: change body background to #F1F1F1 _only_ if it is currently set to white ?

or a way to say: change body background to #F1F1F1 _only_ if it does not already have a background property ?

This will be better as it will prevent changing pages which already change the background property.

Thx !

**Comment by ankit** [comment]
Unfortunately, this will be fairly complex to implement and i can't really think of many use cases where this will be applicable. so closing as won't fix
