### ISSUE TITLE
Site Not Found

### ISSUE THREAD

**Issue by efimov90** [ankit/stylebot#481]
When i try to open stylebot.me today i see this:

Site Not Found
Well, this is awkward. The site you're looking for is not here.

Is stylebot project dies?

**Comment by Phrogz** [comment]
See #466. Ankit last responded about this problem on March 21st. He has not been heard from since.
https://github.com/ankit/stylebot/issues/466#issuecomment-288227540

**Comment by ankit** [comment]
I am actively working on a major release of the extension, with a new UI and lots of new features. The website will come later...
