### ISSUE TITLE
Remove a class

### ISSUE THREAD

**Issue by ashwinash333** [ankit/stylebot#482]
If i have a div with two classes 
Example :
                ` <div class="abc  xyz" `></div>`
and if i want to remove class xyz with stylebot how could i achieve this

**Comment by DejanS** [comment]
Stylebot can change css class rules, not remove class assigned in html

Write css rule for this xyz class, and stylebot will change it.

**Comment by ashwinash333** [comment]
we can only override css ok thanks

**Comment by Nakilon** [comment]
I wish there was a way to replace a class. I.e. there is
```
<svg class="ui-icon__svg ui-icon__svg_size_xs" aria-hidden="true"><use xlink:href="#tick-outline-xs" href="#tick-outline-xs"></use></svg>
```
and I want it to become
```
<svg class="ui-icon__svg ui-icon__svg_size_xl" aria-hidden="true"><use xlink:href="#tick-outline-xs" href="#tick-outline-xs"></use></svg>
```
since there is `-xl` style, that effectively makes svg bigger.
