### ISSUE TITLE
Can't save css properties prefixed with --

### ISSUE THREAD

**Issue by camelofcode** [ankit/stylebot#485]
I am unable to save any css properties prefixed with --.

Trying to make new YouTube look like old youtube. They are using some custom css properties that are non standardly prefixed with '--'.

If I add custom css like:

`#logo {
--yt-swatch-logo-override:rgb(35,35,35);
}
`

then save and reopen, this property has been stripped.

`#logo {
}
`

Chrome devtools allows me to set this style on the element and it updates correctly.

In the meantime I have had to work around this using a separate extension to run custom JS

`document.getElementById("logo").setAttribute("style", "--yt-swatch-logo-override:rgb(35,35,35)"); `

**Comment by camelofcode** [comment]
Looking at how vendor prefixes are handled in the parser https://github.com/ankit/stylebot/blob/master/stylebot/libs/parser.js 

I can totally understand why you would not want to fix this. Never seen a site specific prefix before... YouTube up to no good.

**Comment by MrDemocracy** [comment]
You can disable the new YouTube look, if you didn't already know:
<img width="1280" src="https://user-images.githubusercontent.com/23060864/30633581-79515350-9dec-11e7-8b97-e676449ebe8a.png">

It modifies the "PREF" cookie.
