### ISSUE TITLE
auto backup

### ISSUE THREAD

**Issue by solom2u2** [ankit/stylebot#489]
Is there a way to auto backup styles? I sometime forget to export them and go ahead and delete my Chrome userdata folder, then I remember when it was too late. I hope there is something like emailing the styles every week or so.. or anything to that effect..

**Comment by tobia** [comment]
This would be most useful.

**Comment by ilemhadri** [comment]
Agreed! A much wanted feature.

**Comment by ankit** [comment]
closing as duplicate of #230
