### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Jislkasi** [ankit/stylebot#495]
Anybody home...

Love this extension. I have tried the other one, but this seems much easier to use in combination with Inspect.

Most pressing question... Anybody notice the new random string advertisements? Like on Merriam-Webster.com...

https://www.merriam-webster.com/dictionary/notice

The advertisement at the top is named...
div#XksITAhg.kYPXHwCWCD

They are using randomized strings for their advertisements. Adblock does not block it. Is there any way to block that? I guess not. If not, we should be seeing lots more of those to make the web a much more advertising-friendly place. I have seen it on another major website.

Thanks.

**Comment by quantumleap-** [comment]
Let's challenge Edit CSS directly by clicking the "Edit CSS" button!

Using the browser inspector[F12], **pay attention to the nesting structure of the DOM** and combine the appropriate CSS Selectors.

CSS Selector Reference:
https://www.w3schools.com/cssref/css_selectors.asp

**Comment by Jislkasi** [comment]
That is just spam, right?

**Comment by quantumleap-** [comment]
spam??

**Comment by Jislkasi** [comment]
master of obscurity?

**Comment by ankit** [comment]
v3 is in the works :)
