### ISSUE TITLE
View and Change Bookmarks - why?

### ISSUE THREAD

**Issue by jgwinster** [ankit/stylebot#496]
When I went to install this, I was asked to accept that Stylebot could View and Change Bookmarks.

I can't immediately see why this is necessary. Clearly there might be commercial reasons to want to do this (spot what I am interested, and even substitute a client's site for the site I had bookmarked) so I am nervous about granting the permission. Is there a benign reason I haven't spotted?

**Comment by kurtschwanda** [comment]
I'm also curious about this.

**Comment by ankit** [comment]
An earlier version was using the `bookmarks` api for storage. I have removed that permission now, thanks
