### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by dcrystalj** [ankit/stylebot#498]
at url http://stylebot.me/  i get 
```
Site Not Found
Well, this is awkward. The site you're looking for is not here.
```
Is stylebot down temporary or forever ?

**Comment by Lohoris** [comment]
Given it's been more than 6 months… I'm afraid unfortunately that's it 😔

**Comment by maxstarkenburg** [comment]
Now it's one of those spammy "parked domain" websites with links to who knows where. I got to `stylebot.me` from the `chrome-extension://` pages, which made me wonder if the extension itself was possibly spammy. Not a good look. It would be nice if, at least for now, the website links were removed from the extension itself as well as the Chrome web store, if possible.

**Comment by Lohoris** [comment]
> Now it's one of those spammy "parked domain" websites with links to who knows where. I got to `stylebot.me` from the `chrome-extension://` pages, which made me wonder if the extension itself was possibly spammy. Not a good look. It would be nice if, at least for now, the website links were removed from the extension itself as well as the Chrome web store, if possible.

This repository has been completely abandoned for about two years, nobody's reading it at all as far as I can see.

However, you may try to contact the author, who appears to be this one http://ankitahuja.com/

**Comment by ankit** [comment]
I am now actively working on a completely re-written v3 version, which will be easier to maintain. Stylebot website will come later...but I will have some sync capability built into the version.
