### ISSUE TITLE
Stylebot seems to not support imports

### ISSUE THREAD

**Issue by TheWithered** [ankit/stylebot#501]
Hello,

It seems that Stylebot doesn't support the @import rule, at least not for me. This is quite annoying for me personally as I can't use any custom fonts because of that (e.g. Google Fonts). Even when the import is positioned atop, the font becomes Times New Roman whenever I use one of the fonts that should've been imported. Is this a bug or are imports simply not supported on Stylebot?

If a bug, could it please be investgated? If not, my suggestion would be to allow usage of @import rules.

Best regards

**Comment by easaw** [comment]
Yes, @ankit I'd like this if possible?

**Comment by ankit** [comment]
@easaw yes, this will be fixed in the upcoming v3 release.
