### ISSUE TITLE
Can't use attribute selectors

### ISSUE THREAD

**Issue by aimbob** [ankit/stylebot#504]
Can't use attribute selectors

[aria-label='Main menu']

**Comment by Stocker-jp** [comment]
I couldn't use the following selector either. 
This is necessary to hide "Like" from certain people in TweetDeck.

article[data-key^=favorite_00000000_] {
    display:none;
}

**Comment by ackmanx** [comment]
I can confirm that attribute selectors work, but they don't always take precedence.

**Comment by ackmanx** [comment]
> I couldn't use the following selector either.
> This is necessary to hide "Like" from certain people in TweetDeck.
> 
> article[data-key^=favorite_00000000_] {
> display:none;
> }

Make sure to quote your value too

```
article[data-key^="favorite_00000000_"] {
    display:none;
}
```

**Comment by Stocker-jp** [comment]
In my environment, the following values cannot be stored
It will be deleted automatically.

```
article[data-key^="favorite_00000000_"] {
    display:none;
}
```

**Comment by ankit** [comment]
this should now work in v3
