### ISSUE TITLE
Crash out of memory when trying to write nth selector.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [ankit/stylebot#505]
Crashing when trying to type nth selector with the open bracket....
![image](https://user-images.githubusercontent.com/1968109/41389119-2bf69fce-6fe3-11e8-8747-79de0b6094a5.png)

Expected result: Just don't parse the CSS and break out.

Duplicate #249

**Comment by fachalady** [comment]
I'm having the same issue. I literally cant get past ":nth-child(_)" before the tab freezes, I get the "debugging connection was lost" popup and then crashes.
