### ISSUE TITLE
Toggle style on or off

### ISSUE THREAD

**Issue by taylorsmurphy** [ankit/stylebot#508]
Imagine you hide a sidebar on a website, but occasionally need to restore the sidebar to click a link on it.

In Stylebot, the dropdown menu only allows you permanently delete the style and remove it. To toggle it off, you have to go into the Settings page, then to the Styles section, then uncheck the style. To re-enable it, you must do the same thing.

"Toggle style <on/off>" should be part of the menu in this extension! If the developer ever gets time to make some changes, this would be great addition

**Comment by dnewell** [comment]
This issue was moved to dnewell/stylebot#1

**Comment by ankit** [comment]
This is now supported. thanks
