### ISSUE TITLE
Stylebot has stopped working altogether

### ISSUE THREAD

**Issue by Lohoris** [ankit/stylebot#512]
Yesterday, for me, Stylebot has stopped working altogether.

- The icon is sometimes blank
- Left clicking it did nothing at all
- The CSS of already-edited pages weren't changed anymore

Given that the site is expired, and this github is abandoned, I'd say this extension is finally gone for good.

That being said, maybe it stopped working only for some and not for everyone, so I'm posting here in case anyone has any useful tip.

**Comment by Lohoris** [comment]
> get/check this one ... https://github.com/Icebird/stylebot

Well, it works, so thanks!

However I'm a bit concerned by the fact that it hasn't been updated in 1 year, and it doesn't even have a public issue tracker… I assume that has been abandoned too?

**Comment by rls-vault** [comment]
ditto

Mac 10.14.2 (18C54)
Google Chrome is up to date
Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by ankit** [comment]
I am actively working on a v3 release (re-write) which should fix a lot of the issues and will be more maintainable.
