### ISSUE TITLE
[Feature Request] Support Firefox

### ISSUE THREAD

**Issue by blackoutworm** [ankit/stylebot#519]
Hi there. I've been using this extension for the longest time.
But now that I'm using Firefox, I need to find a good alternative. Haven't been able to.
I also tried installing the extension using Foxified, which is a firefox addon that'll allow you to use "some" Chrome extensions in Firefox.
I realize that coding this extension to work with Firefox would require a ton of work and possibly even re-coding the entire extension.
So do you think you could at least make it work that way?

**Comment by ankit** [comment]
I've heard Firefox uses the same architecture as Chrome now, so I will investigate this.

**Comment by ankit** [comment]
I was able to investigate and this seems very doable with the latest version of Firefox. I will be repurposing this issue to include any tasks for supporting Firefox

**Comment by ankit** [comment]
Now available on firefox - https://addons.mozilla.org/en-US/firefox/addon/stylebot-web/ 🥳
