### ISSUE TITLE
Edit CSS is missing exit button

### ISSUE THREAD

**Issue by JacRossiter** [ankit/stylebot#521]
There's no way to exit or save in the edit css window. It used to be there but for the past few months it has been gone.

**Comment by rob49152** [comment]
I have just started having this issue as well. Very annoying.

**Comment by rob49152** [comment]
Found you can edit the CSS in the stylebot options screen. Now slightly less annoying.

**Comment by ankit** [comment]
The editor UI will be much improved in the upcoming v3 release. And the "Code" mode will have a way to close the window
