### ISSUE TITLE
!important property doesn't work

### ISSUE THREAD

**Issue by jlauerswi** [ankit/stylebot#524]
I don't know if it's in all cases, but when I was trying to override inline styling the !important property, Stylebot was removing it.

In my scenario the pages html had this:
`<tr style="color:Black;background-color:White;">
			</tr>`
and I was trying to use Stylebot to override this with:
`[style*="background-color: White"] {
    background-color: pink !important;
}`

This definitely works with css, I've tested it, and I found the trick at https://css-tricks.com/override-inline-styles-with-css/.

When I add !important in the CSS Editor and click Save, it is removed.

**Comment by quantumleap-** [comment]
stylebot automatically(forcibly) adds "!important" to the style actually applied to the page.

Check the "style actually applied to the page" in the following steps!
1) F12(DevToolsOpen)
2) Ctrl+Shif+C(select element mode)
3) click target element
4) check the Styles tab in Elements tab in DevTools.

**Comment by jlauerswi** [comment]
I'm sorry, you are right.

My problem turned out to be letter casing. I didn't know css cared about the casing of the colors in the selector.

It my problem was that I had:
`<tr style="color:Black;background-color:white;"> </tr>`
and
`[style*="background-color: White"] { background-color: pink !important; }`

One is uppercase "White," and the other is lowercase "white."
