### ISSUE TITLE
Further updates

### ISSUE THREAD

**Issue by Bamajon1974** [ankit/stylebot#530]
Will StyleBot ever be updated and maintained/developed anymore? Looks like it hasn't been updated in at least 2 years. 

Thanks in advance!

**Comment by ankit** [comment]
I have started working on it again and plan to give it at least one major refresh. It's going to take some time since it's really old code :)

**Comment by Bamajon1974** [comment]
Thank you. If it is any help, someone else forked Stylebot to Stylebot Lite. 

https://chrome.google.com/webstore/detail/stylebot-lite/lkcdgdbfbbnpnljlalmcjnepgjnmgigh?hl=en-US
