### ISSUE TITLE
Stylebot won't copy edited CSS code

### ISSUE THREAD

**Issue by eadmin2** [ankit/stylebot#532]
When I make a CSS change with stylebot and click edit CSS at the bottom left, I see the new code and hit Copy at the bottom left, but it doesn't copy anything.  I also hit ctrl c and even right click, but there is no option to copy the text.

**Comment by wadawada** [comment]
select and right click won't show copy/paste on the right click menu

**Comment by ankit** [comment]
should now work in v3
