### ISSUE TITLE
Stylebot.me Website No Longer Working

### ISSUE THREAD

**Issue by Tantumonium** [ankit/stylebot#535]
The entire http://stylebot.me/ website is no longer working. This includes all previously community created/shared styles as well as any additional help/support resources. :(

**Comment by ankit** [comment]
I have removed references to the stylebot social and updated the README with resources until I can bring the website back up. It will take some time but I hope to bring it back up.

**Comment by Avivhdr** [comment]
Hi @ankit,
Any news on bringing the site back?
