### ISSUE TITLE
css variables

### ISSUE THREAD

**Issue by LucianoBestia** [ankit/stylebot#540]
The website 
<https://web.crev.dev/rust-reviews/crate/num-traits/>
has css variables for the color palette:
```css
         :root {
            /* color palette */
            /* use of variables: var(--b_color_05); */
            /* background color */
            --b_color_01: #24292E;
            --b_color_02: #1B1D23;
            --b_color_03: #181A1F;
            --b_color_04: #333842;
            /* front color */
            --f_color_01: #FBF462;
            --f_color_02: #9DA5B4;
            --f_color_03: #78C379;
            /* border color*/
            --brd_color_01: #000;
            --brd_color_02: #eaecef;
        }
```
I tried to copy this to Stylebot css, but it didn't work. When I change it and save it strips away the lines with the variables. 
Is it possible to overwrite "css variables" with Stylebot? is there a special procedure?

**Comment by quantumleap-** [comment]
The only way to do this is to rewrite the code as follows.
(First, you need to copy the entire folder of this extension somewhere.)

/libs/parser.js

before:
> // SPC !   "   #   $   %   &   '   (   )   *   +   ,   -   .   /
     W,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  I,  0,  0,

after:
>   // SPC !   "   #   $   %   &   '   (   )   *   +   ,   -   .   /
     W,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  SI,  0,  0,

**Comment by LucianoBestia** [comment]
Thanks. I found the extension "user css" that can just do this.
No problem.

**Comment by ankit** [comment]
@LucianoBestia variables will be supported in the upcoming v3 release, which will also include lots of other cool features. Hope you try stylebot again once v3 is released! the latest version will use https://postcss.org/

**Comment by ankit** [comment]
just released v3, so this should now work
