### ISSUE TITLE
URL Pattern for iframes with no src?

### ISSUE THREAD

**Issue by tobia** [ankit/stylebot#542]
Hello

I'm trying to style [Kindle Cloud Reader](https://read.amazon.com/) in order to remove the 10% white margins (5% on each side) and make the images larger. (I use it with the screen in portrait mode to read manga, which has small writing, so making things 10% larger matters.)

But they have a few nested iframes (why do they do that!?) and the last one has no `src` attribute. [Here is a discussion](https://stackoverflow.com/questions/18044073/iframe-without-src-but-still-has-content) on iframes with no src attribute.

How can I apply a custom style to those? Can we make the `*` selector apply to iframes with no source? Or better yet, treat those iframes as if they were on the domain of their parent frame?

I'll admit I know nothing of the specific browser hooks Stylebot uses to inject its `<style>` tag, and I'm sure an iframe with no src goes through a different process than standard ones. So maybe it's not possible. But if it is, I think it would be useful.

PS. I managed to solve my use case without it, but the question remains. (In case anybody comes here from Google specifically for the Kindle margin thing, what I did was: `#kindleReader_content.no_title iframe { transform: scale(1.11); }` where 1.11 is the inverse of 90%. This solves the problem without messing with all their margins and nested frames.)

**Comment by ankit** [comment]
I am glad you were able to figure this out @tobia. I will try and see if I can implement a good default behavior

**Comment by taylordolan** [comment]
I see that this was closed as completed. Does that mean there's a way to target iframes with no src? I've been trying to do this with no luck so far.
