### ISSUE TITLE
Need scroll to save style in option page

### ISSUE THREAD

**Issue by zenkarsha** [ankit/stylebot#546]
HI, again

I am using 11 inch laptop, and my screen is really small that I can't see the "Save" button, so I need to zoom out the window to see entire editor zone, then save the code. I try to add custom style for this extension itself and doesn't work. 😕

![Screen Shot 2020-07-11 at 23 01 06](https://user-images.githubusercontent.com/63251735/87227139-6ea05480-c3cb-11ea-94f6-dc8fd3b1413a.png)

![Screen Shot 2020-07-11 at 23 08 03](https://user-images.githubusercontent.com/63251735/87227144-75c76280-c3cb-11ea-9c69-f9b039318969.png)

**Comment by ankit** [comment]
I will fix the bug so you can see the save button in the v3 release. Thanks for flagging. 
You cannot add a custom style for this extension.
