### ISSUE TITLE
Can't select elements

### ISSUE THREAD

**Issue by KDCCreative** [ankit/stylebot#548]
As of yesterday (7/11/20), the element selector in Stylebot no longer functions. The drop down menu of elements to select can't detect anything, either. Right clicking on an element doesn't show the prompt to edit with Stylebot. All of my previous changes (which could easily be redone) have been deleted as well. I tried removing and reinstalling the extension, but this didn't fix the issue. Is there anything I can do to fix this, or do I just need to wait for an update?

**Comment by ankit** [comment]
Is it not working on all pages or a specific page? If it is for a particular page, i can try to fix it in the newer version
I am still able to select elements with the older version.

**Comment by KDCCreative** [comment]
It originated on Youtube, but it's now on all pages. If it's just a bug with my version of the program, I may just have to wait to troubleshoot further.
To clarify on the selection not working, you can click the button to select an element, and elements are outlined in green to select them, but clicking does nothing.

**Comment by ankit** [comment]
@KDCCreative I think at this point, it will best to wait for the new release, since I have completely re-written the extension and it is going to be way easier to maintain and fix bugs. 

After the release, if your bug persists, it would be easier to resolve.

**Comment by KDCCreative** [comment]
Alright, I'll let you know if the issue persists. Thanks for your help.

**Comment by ankit** [comment]
the new version is out. @KDCCreative hopefully it works for you
