### ISSUE TITLE
Installing 2.2, how?

### ISSUE THREAD

**Issue by dm2912** [ankit/stylebot#557]
Can someone explain how you compile/install v2.2 into chrome (actually vivaldi).

Downloaded 2.2 from the releases but its not obvious how to import it into chrome

(I realise 2.2 is not developed and has "bugs" but honestly its been working fine for me for many years and i really dislike the interface of v3 with a passion :D)

**Comment by lsggss** [comment]
Download -> unzip, then go "chrome://extensions/", turn on "Developer mode" on top right corner, choose "load unpacked", navigate to the path of the unzip folder.

**Comment by ankit** [comment]
thanks @lsggss. 

@dm2912 Sad to hear you don't like the new design. Feel free to create individual tickets for feedback. The above steps will work, you will just need to select the "stylebot" folder in the unizipped folder
