### ISSUE TITLE
Stylebot 3.0 breaks cnet.com

### ISSUE THREAD

**Issue by raypaw** [ankit/stylebot#562]
When Stylebot 3.0 is enabled, the CNET website breaks in the users local browser. Two ways this manifests is that ads don't display and an error is seen in the console.

Verified in a fresh Chrome profile with no other extensions.

Stylebot disabled:
<img width="1420" alt="stylebot-disabled" src="https://user-images.githubusercontent.com/19699648/88866349-4ed8a100-d1bf-11ea-8771-cadc4898b2a2.png">

Stylebot enabled
<img width="1415" alt="stylebot-enabled" src="https://user-images.githubusercontent.com/19699648/88866350-4f713780-d1bf-11ea-8e32-f868540dfd02.png">

**Comment by ankit** [comment]
@raypaw thanks for reporting, i will work on a bugfix

**Comment by raypaw** [comment]
@ankit congratulations on 3.0 and thanks for the great extension!
