### ISSUE TITLE
Default Option + S keyboard shortcut hijacks a Polish letter "ś"

### ISSUE THREAD

**Issue by adamkarminski** [ankit/stylebot#563]
**Describe the bug**
Option + S/A/Z/X/C/E/O is used in Polish to write Polish characters. The default keyboard shortucts you introduced in Stylebot 3.0 made me lose 2h looking for a reason why the letter "ś" stopped working in my Chrome.

I suggest changing the default shortcuts as they are probably used in other languages too.

**To Reproduce**
- Use MacOS, turn on the Polish Pro keyboard layout (standard for Polish keyboards) 
- Try typing Option + S anywhere in Chrome (addreess bar, input fileds)

**Expected behavior**
Letter "ś" should appear.

**Comment by ankit** [comment]
Sorry about that @adamkarminski, thanks for reporting. I will update the default global shortcuts to include Ctrl modifier key. I didn't expect Chrome to actually prevent the default behavior when typing in an input with their commands API.
