### ISSUE TITLE
[Bug] Stylebot break xml files

### ISSUE THREAD

**Issue by viclafouch** [ankit/stylebot#565]
**Describe the bug**
When I'm on an xml file, css stylebot is included directly to the xml file. 

**To Reproduce**
- Install stylebot
- Go to https://www.victor-de-la-fouchardiere.fr/sitemap.xml
- Scroll down
![image](https://user-images.githubusercontent.com/23353836/88973281-20d68800-d2b7-11ea-9445-e86a13869509.png)

**Comment by ankit** [comment]
thanks for reporting @viclafouch. i already have a fix submitted to the Chrome Webstore for review, so you should be getting an update with a fix soon-ish
