### ISSUE TITLE
[Bug] Stylebot turns github to black/white only

### ISSUE THREAD

**Issue by timo-schmid** [ankit/stylebot#566]
**Describe the bug**
The whole github.com site turns black/white/gray only. Same goes for internal github sites.

**To Reproduce**
- Go to 'github.com'

**Expected behavior**
Colors.

**Screenshots**
It's pretty obvious.

**Additional context**
Turning off the extension fixes the issue.

**Comment by timo-schmid** [comment]
Seems there is an entry "git" that contains:
```
div.position-relative.js-header-wrapper {
  filter: grayscale(100%);
}

div.show-on-focus {
  filter: grayscale(100%);
}

#js-flash-container {
  filter: grayscale(100%);
}

div.application-main {
  filter: grayscale(100%);
}

div.footer.container-lg.width-full.p-responsive {
  filter: grayscale(100%);
}

div.ajax-error-message.flash.flash-error {
  filter: grayscale(100%);
}

div.js-stale-session-flash.stale-session-flash.flash.flash-warn.flash-banner {
  filter: grayscale(100%);
}

#site-details-dialog {
  filter: grayscale(100%);
}

div.Popover.js-hovercard-content.position-absolute {
  filter: grayscale(100%);
}

div.js-global-screen-reader-notice.sr-only {
  filter: grayscale(100%);
}

div.chrome_websiteIP_right {
  filter: grayscale(100%);
}
```

But I don't remember adding this, does it come with the extension?

**Comment by ankit** [comment]
@timo-schmid You might have accidentally enabled grayscale mode. You can remove this css by going into "magic" tab and disabling grayscale (or just manually deleting css). There is a global shortcut (Alt+G) to toggle grayscale and you might have pressed those keys.

**Comment by ankit** [comment]
I am removing the default shortcuts for grayscale/readability so that will make this more stable.

**Comment by timo-schmid** [comment]
It's quite likely I hit the keyboard shortcut, thanks! 👍
