### ISSUE TITLE
[Bug] Default Option + G keyboard shortcut hijacks a German (Switzerland) letter "@"

### ISSUE THREAD

**Issue by haslo** [ankit/stylebot#568]
**Describe the bug**

Similarly to #563: The German (Switzerland) keyboard has the "@" character as "Alt+G". This is shadowed by a default shortcut from 3.0.

**To Reproduce**

- Use German (Switzerland) keyboard driver
- Try typing Option + G anywhere in Chrome (address bar, input fields)

**Expected behavior**
Character "@" should appear.

**Comment by ankit** [comment]
Thanks for reporting @haslo. The fix for #563 will also fix this and is already in webstore review. Closing as duplicate.
