### ISSUE TITLE
[Bug] Not effective to file URL (since v 2.4.0)

### ISSUE THREAD

**Issue by github-kk** [ankit/stylebot#569]
**Describe the bug**
The file URL permission is set to enabled in the Extension setup. It worked in version 2.3.0. It stopped working since 2.4.0 and 3.0. 
OS: Ubuntu 18.04
Browser: chromium 

**To Reproduce**
- load a file URL. The stylebot is not applied. 

**Expected behavior**
- it worked in version 2.3.0. Same display behavior as online webpage. 

**Screenshots**

**Additional context**

**Comment by ankit** [comment]
@github-kk I am actually not able to reproduce this in Chrome, I am able to open stylebot in a `file://` URL.  Can you confirm this happens for all `file://` urls and not just a specific site?
