### ISSUE TITLE
Why stylebot add index.css to all website?

### ISSUE THREAD

**Issue by k79e** [ankit/stylebot#571]
It updated to v3 today and I find that.
Is it normal?

It added a index.css (chrome-extension://oiaejidbmkiecgbjeifoejpgmdaleoha/editor/index.css) and https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500&display=swap

Even if I disable all rules it still add these css automatically.

**Comment by ankit** [comment]
@k79e yes, the css is added for the stylebot editor. it should not conflict with any other elements on the page. are you noticing any side effects in terms of performance?

if yes, I can do an optimization to only inject this css when the editor is opened (and not inject it by default).

**Comment by k79e** [comment]
Is this necessary? It even load two css when I only open a picture. And this second css is loading some woff fonts.
Loading these thing on other website will make the load time become wrong.

I think even if there don't exist any problem it still should not add these css to other website.
Because you make this behavior out of control from user. It will be horrible.

**Comment by WORMSS** [comment]
Can we please remove this? I am doing load timing for websites I have a simple `display: none` on an element on. I don't need font loading.

**Comment by ankit** [comment]
@k79e thanks for bringing this up. I will have a fix in the next release.

**Comment by WORMSS** [comment]
Typical, the day after I uninstalled the extension, you fix it.
