### ISSUE TITLE
[Bug] Completely breaks Xero's Leave page in My Payroll

### ISSUE THREAD

**Issue by ZimbiX** [ankit/stylebot#572]
I have no idea how, but this extension completely breaks Xero's Leave page in My Payroll! =( Unless I have this extension disabled, the page forever just shows the loading indicator.

![Screenshot from 2020-08-05 14-07-46-censored](https://user-images.githubusercontent.com/2916331/89370942-4d5e2a00-d725-11ea-8e7a-4251e6dabc1e.png)

This is the failing URL:

https://edge.xero.com/people/payroll/payrollui/27.73.0/app/viewmodels/employee-portal/viewmodels/employee-portal/timeoff.js

but oddly, when the extension is disabled, it loads this URL instead:

https://edge.xero.com/people/payroll/payrollui/27.73.0/app/viewmodels/employee-portal/timeoff.js

Edit: This may be related to #570

**Comment by ankit** [comment]
thanks for reporting here @ZimbiX, it is very helpful. I will have a fix out soon in a release. I will let you know when the update is published on the Chrome Webstore so you can help me test this out.

**Comment by ankit** [comment]
@ZimbiX This should now be resolved in the latest update. Please let me know if it fixed the issue, thanks!
