### ISSUE TITLE
[Bug] No code displayed

### ISSUE THREAD

**Issue by Marubozu** [ankit/stylebot#576]
**Describe the bug**
On some websites only, not all of them, there is no code displayed.

Please see video : https://youtu.be/VIlDz2nARac

**Comment by ankit** [comment]
thanks for reporting @Marubozu and recording the video. 
I am actually not able to reproduce this, but I am guessing there is an edge case where this bug happens. 

A few things will help me further debug this:
1) Can you include the example CSS here
2) Are you able to reproduce this consistently on bitfinex.com or it only happens for some specific cases?
2) Can you see and report if there are any javascript errors in the Chrome console when you are using stylebot code editor?

**Comment by Marubozu** [comment]
Hello, I am no longer able to reproduce this issue. However, please note the following:
1. This issue was lasting for a while on Bitfinex, but it is now gone, by magic.
2. This is not the first time this is happening, and not only with Bitfinex.
3. This was happening with the previous version of Stylebot, before this major update, so this is not related to the upgrade.

I'll keep an eye on it and will update the ticket if I come across this issue again.

**Comment by ankit** [comment]
Thanks @Marubozu
