### ISSUE TITLE
I NEED HELP WITH THIS!

### ISSUE THREAD

**Issue by MrPdtech** [ankit/stylebot#582]
Hello Ankit,
How are you brother?
So i was trying to replace these logos with your program but i can't seem to get it to work (unfortunately this is beyond me as i'm not a coder).

However, i could hide them (with `image#their-ids` in the codes below), but that's not what i want. i want to replace them with my own image (as i've usually done on other websites). so i thought that if they can be hidden, certainly they can be replaced and. So decided to bring my issue to the best coder in the world.
Could you please kindly take a look at it. I'm really sorry to bother you.

**Url to the Site:** https://tracker-2.namitiyu.com/en/football/animate?profile=YOvEiPHNNhaHB&id=3399599&timezone=08%3A00

**HTML paths of the logos:** `<image id="center-bar-defaults" width="94.73684210526315" height="12" xlink:href="https://s.namitiyu.com/tracker/bar/21e9752dff!w150" initCenterBar="true" class=""></image>`

`<image id="center-bar-defaults" width="94.73684210526315" height="12" xlink:href="https://s.namitiyu.com/tracker/bar/21e9752dff!w150" initCenterBar="true" class=""></image>`

`<image id="center-bar-advert1" width="94.73684210526315" height="12" xlink:href="https://s.namitiyu.com/tracker/bar/21e9752dff!w150" initCenterBar="true" class=""></image>`

`<image id="center-bar-advert2" width="94.73684210526315" height="12" xlink:href="https://s.namitiyu.com/tracker/bar/21e9752dff!w150" initCenterBar="true" class=""></image>`

`<image id="center-bar-advert3" width="94.73684210526315" height="12" xlink:href="https://s.namitiyu.com/tracker/bar/21e9752dff!w150" initCenterBar="true" class=""></image>`

`<image height="32" x="502.7441860465117" y="32" xlink:href="https://s.namitiyu.com/tracker/icon/5389c5e8a2!w300" class="customer-logo" style="opacity: 1;"></image>`

**Image i want to replace them with (My Own image):** https://i.imgur.com/F6foNGL.png

Thanks a lot. I anticipate your response sir.

**Comment by ankit** [comment]
you could try using the `::after` (https://developer.mozilla.org/en-US/docs/Web/CSS/::after) to inject HTML content. I gave it a brief go but couldn't really get it to work with `image` elements. 

In the future, I may experiment with allowing stylebot to change HTML content, but I can't promise anything. Closing the issue.
