### ISSUE TITLE
[Feature Request] Please add style for group site

### ISSUE THREAD

**Issue by ariews** [ankit/stylebot#590]
First, thank you to the developer for creating such great extension. It really helps me.

There are so many templates out there, and many sites used this template. Because of this, we need to add same styles for every sites. So I think, it would be very helpful if Stylebot has option for group site.

**Comment by ankit** [comment]
@ariews you can group multiple sites by editing the URL in the options page. For example: `google.com, gmail.com` will apply the same css to both `google.com` and `gmail.com`
