### ISSUE TITLE
[Feature Request] Wildcard character support in URLs

### ISSUE THREAD

**Issue by lizfischer** [ankit/stylebot#592]
I need to change the style on many pages with a similar URL structure. I would like to be able to replace parts of the URL string with * to match any characters in that part of the string. For example, I would like this "https://d.lib.rochester.edu/teams/text/*" to match any URL beginning with "https://d.lib.rochester.edu/teams/text/"

**Comment by ankit** [comment]
@lizfischer sorry for the late reply. you can already do this by using `**` -> `https://d.lib.rochester.edu/teams/text/**" should work and match any `/`. You can edit the URL via the options page. You can see the documentation on the supported wildcards and how to use regex in the Help tab in Stylebot Options.
