### ISSUE TITLE
[Bug] Color bar picks wrong color on first selection

### ISSUE THREAD

**Issue by Higurashi-kagome** [ankit/stylebot#595]
**Describe the bug**
When I chose an element and try to change its background color by clicking the color bar, the color bar jumps to a wrong position.

**To Reproduce**
- Open styletbot and select an element.
- Click on 'Background'.
- Click the color bar：
![image](https://user-images.githubusercontent.com/51501079/97793285-1d8bc900-1c25-11eb-9928-872b2c820a7f.png)
 
**Expected behavior**
It should jump to the position I just clicked, but it jumped to the end of the color bar.

**Screenshots**
![stylebot-issue-colorbar](https://user-images.githubusercontent.com/51501079/97793339-9e4ac500-1c25-11eb-9790-bc87aeed8208.gif)

**Comment by ankit** [comment]
@liuhao326 thanks for reporting the issue and the helpful GIF! I can reproduce and will fix in a future release.

**Comment by ankit** [comment]
Merged. will be available in [v3.1](https://github.com/ankit/stylebot/milestone/8)
