### ISSUE TITLE
[Bug]Ctrl C disturbed by stylebot editor

### ISSUE THREAD

**Issue by Higurashi-kagome** [ankit/stylebot#596]
**Describe the bug**
When I try to copy some text on the web by "Ctrl + C" after opening stylebot editor, it will not copy successfully but switch to code editor. I guess the keyboard shortcut is the reason for :

![image](https://user-images.githubusercontent.com/51501079/97794319-3307ef80-1c33-11eb-9389-8b3cd139341a.png)

**To Reproduce**
- Open styletbot.
- Select a text on the web and copy it by "Ctrl + C".

**Expected behavior**
It should copy successfully rather than opening stylebot editor.

**Comment by ankit** [comment]
Thanks for reporting! will fix.
