### ISSUE TITLE
Readabilty dark mode

### ISSUE THREAD

**Issue by herrigor** [ankit/stylebot#606]
How do I activate Readability dark mode?
There is the `stylebot-reader light` classes in the elements from Readability, I can inspect and change to `stylebot-reader dark` then Stylebot will apply its own dark mode. But how can I make that the default?

I couldn't find it in the extension options or the help section.
Thanks!

**Comment by ankit** [comment]
@herrigor you can enable the dark readability mode by selecting the "Dark" theme in the "Magic" tab in the stylebot editor. 

<img width="330" alt="Screen Shot 2020-12-30 at 5 16 37 PM" src="https://user-images.githubusercontent.com/61857/103389288-e1f56a00-4ac2-11eb-8aee-dce06a84f27c.png">
