### ISSUE TITLE
[Feature Request] Add option to disable web-based suggestions/tooltips

### ISSUE THREAD

**Issue by erayrafet** [ankit/stylebot#607]
**Is your feature request related to a problem? Please describe.**
Quite often, I accidentally click the tooltips and get redirected to MDN, etc.

**Describe the solution you'd like**
I would like to see a toggle for the tooltips feature.

**Additional context**
![image](https://user-images.githubusercontent.com/34194191/102862122-4ff1bf80-4439-11eb-8598-c24f8ece19cc.png)

**Comment by ankit** [comment]
thanks @erayrafet - these will be disabled in the upcoming release. the space is too limited for these to be uesful

**Comment by ankit** [comment]
Merged. will be included in [v3.1](https://github.com/ankit/stylebot/milestone/8)
