### ISSUE TITLE
[Bug] Unable to open Stylebot after Chrome crash

### ISSUE THREAD

**Issue by KDCCreative** [ankit/stylebot#610]
The title sums it up fairly well. I haven't tried to reproduce this issue, nor do I want to try to as it involves crashing the program. I was viewing a large Google Doc with a few other tabs open, one of which was pinned and another was playing audio. The Docs tab seemed to take up too much of some resource and caused my entire Chrome app to crash.
Upon reopening Chrome, Stylebot no longer worked. It had been working perfectly before the crash, and I've had a similar issue on a previous version of Stylebot, with the same symptoms but no Chrome crash to start out with. Stylebot is unable to be opened on any page, cannot be selected upon right-clicking an element on a page (see image attached), and I don't have the CSS knowledge to code something purely in the editor on the Stylebot options website, so I can't test whether it is completely unable to access pages' CSS. All of my previous CSS settings have been wiped. I never backed them up, which is seeming like a good idea now that this has happened twice. Another Chrome extension, Tampermonkey, also came up with a report noting irretrievable user settings and data. I no longer use this extension, but it may be of note in finding and addressing the issue here if there is one.
![image](https://user-images.githubusercontent.com/68196110/103147436-a6e9e400-471a-11eb-9662-e6219bf6bb32.png)
Removing and re-installing Stylebot from the Chrome extension webstore has not fixed this issue.

**Comment by ankit** [comment]
@KDCCreative It will be very helpful if you can check if the extension's popup, background page or the page you try to open stylebot on has any Javascript errors in the developer console. Without that information, it is hard for me to know what the issue is. Thanks!

**Comment by KDCCreative** [comment]
I've found two errors (after googling how to open the dev console, lol) that might be of note here.
![image](https://user-images.githubusercontent.com/68196110/103617179-67c64a80-4ef3-11eb-818d-9fb50bbcd279.png)
The first error is seen on every page in Chrome. I don't know if it's Stylebot-related, another extension possibly breaking, or another Chrome issue.
The second error appears on some pages, but not others. Notably, it does not appear on a freshly opened tab with Google still open, but all other tabs I've tried had it show up. It seems like it could be the issue?
Thanks for responding!

**Comment by ankit** [comment]
Thanks for the quick response! this is very helpful. Yes, it is likely the second error is the issue. Which browser version are you on?

**Comment by KDCCreative** [comment]
Sorry for the late reply, it was 2am when I last responded, but I've dug into those for ya.
I'm running Chrome version 87.0.4280.88 (latest, apparently) on Windows 10.
Here's what came up on the background page:
![image](https://user-images.githubusercontent.com/68196110/103712797-58411300-4f80-11eb-8d42-d2ec1b879f63.png)

**Comment by ankit** [comment]
@KDCCreative no worries, thanks! Sorry another quick help: can you run `chrome.storage.local.get(items => console.log(items))` and copy the output here? Thank you!

**Comment by KDCCreative** [comment]
![image](https://user-images.githubusercontent.com/68196110/103713407-dce06100-4f81-11eb-96f0-ca195d7373cb.png)
Or, if you need it as text:
Unchecked runtime.lastError: IO error: .../LOCK: File currently in use. (ChromeMethodBFE: 15::LockFile::2)

**Comment by thewhoami7** [comment]
thx this help me full
