### ISSUE TITLE
[Bug] Toggle to enable/disable a website's style isn't working

### ISSUE THREAD

**Issue by facederpface** [ankit/stylebot#615]
**Describe the bug**
I'm not exactly sure when it happened, but recently I noticed I am unable to disable a style set on a website. The toggle switch seems to be stuck on, and the only way to disable the style is to disable the extension or remove it.

**To Reproduce**
- Click on the Stylebot extension icon in the top-right extensions bar
- Click on the website's style toggle switch

**Expected behavior**
The switch should turn the style on and off, but it is stuck in the on position.

**Additional context**
I'm using the latest version of Chrome.

**Comment by ankit** [comment]
@facederpface Thanks for reporting. I already have a bugfix for this issue submitted to the Chrome Webstore in version 3.0.7. Should be available soon!

**Comment by facederpface** [comment]
Works! Thank you!
