### ISSUE TITLE
[Feature Request] Dynamic width of sidebar window

### ISSUE THREAD

**Issue by Icebird** [ankit/stylebot#616]
Sometimes I am unable to clearly read the custom CSS for a site in the sidebar due to its 320px width restriction.

I would like to be able to adjust the width of the sidebar when editing CSS code for visibility, or at least have the width be relative to the browser width.  20-25% seems to work well for me.  This setting does not necessarily have to persist.

![image](https://user-images.githubusercontent.com/672202/103560555-f4d2ba80-4e85-11eb-8615-cfa4a96656f2.png)

**Comment by ankit** [comment]
Yes, I have thought about making the sidebar resizable, I will take a look, thanks!

**Comment by ankit** [comment]
Merged. will be included in [v3.1](https://github.com/ankit/stylebot/milestone/8)
