### ISSUE TITLE
[Feature Request] Multiple Global style sheets that can be independently switched on and off

### ISSUE THREAD

**Issue by lloydi** [ankit/stylebot#620]
I would like the ability to switch on or off specific user styles which can be applied to any and every site.

Currently, using the* wildcard selector, I can create a user style that applies to every website.

What I would like is the ability to create multiple user style sheets that can also apply to any website, but can be named in a way to identify what's switching them on or off will do.

For example, I may wish to have one globally available stylesheet that highlights all headings. In a separate globally available stone sheets I may want to highlight images. The best analogy I have is to think of the kind of configuration options that are available using the web developer toolbar from Chris Pederick, which would allow me to select which options I wish to reveal for any website, and be able to continue configuring and adding new options as I choose.

Is this something that you might be able to accommodate?

Thank you

**Comment by ankit** [comment]
Thanks @lloydi - that does sound very useful.

**Comment by ankit** [comment]
@lloydi I am going to close this issue and merge it into #621 - since both will require a similar implementation
