### ISSUE TITLE
[Bug] Installing it from scratch no longer works

### ISSUE THREAD

**Issue by Lohoris** [ankit/stylebot#622]
**Describe the bug**
I've created a new Chrome profile and tried to install Stylebot, but the new version doesn't seem to work.

My old one has id `lkcdgdbfbbnpnljlalmcjnepgjnmgigh`, and the new one `oiaejidbmkiecgbjeifoejpgmdaleoha`, which is what I can find in the store.

The new version isn't applying the styles I've imported, and it doesn't open (neither with right click style element, nor with "open stylebot").

I'm completely at a loss, no idea what am I supposed to do to get it running.

I've also tried to simply copy the whole folder from one profile to another one, but it says that the extension is damaged or something.

**Comment by ankit** [comment]
@Lohoris hmm, i am not sure your older one would have the id `lkcdgdbfbbnpnljlalmcjnepgjnmgigh`. would need your help to debug this:

- if you go to `chrome://extensions`, do you see any errors for Stylebot? 
- can you also paste the export from your older extension
- are you seeing any javascript errors on a page when you try to open stylebot?

**Comment by Lohoris** [comment]
I wasn't able to reproduce this on a new machine, but I'll try to reproduce it again on the machine where this bug originated. I'll keep you updated.
