### ISSUE TITLE
[Bug] Hightlight area not fixed on the element

### ISSUE THREAD

**Issue by Higurashi-kagome** [ankit/stylebot#626]
**Describe the bug**
Stylebot will highlight the elements selected by the CSS selector, but it seems that the highlight area is not fix on the elements when scrolling the web page.

**To Reproduce**
- Go to [Tom Preston-Werner](https://tom.preston-werner.com/)
- Click Stylebot and then click the selector arrow for selecting
- Select some elements
- Click the selector input box, and the elements will be highlighted
- Scroll the page, will find the highlighted area did not scroll with the elements

**Expected behavior**
The highlighted areas should always be fixed on the elements.

**Screenshots**

<details>
<summary>Details</summary>

![demo](https://user-images.githubusercontent.com/51501079/113671072-771e8500-96e8-11eb-83f2-c06a165e18bb.gif)

</details>

**Comment by ankit** [comment]
thanks @Higurashi-kagome for the detailed description.
