### ISSUE TITLE
[Bug] Just trigger the style of the current tab

### ISSUE THREAD

**Issue by Higurashi-kagome** [ankit/stylebot#630]
**Describe the bug**

When opened multiple tabs of a website and then trigger the StylBot style, the style will only apply to the current tab.

**To Reproduce**

- Go to [Tom Preston-Werner](https://tom.preston-werner.com/)
- Add the style for the website:

	```CSS
	  .title a{
	    font-size: large;
	  }
	```
- Turn off the style:
	  <details>
	  <summary>Details</summary>
		![image](https://user-images.githubusercontent.com/51501079/113971697-dd7fe080-986b-11eb-99c2-5ba4a602ff74.png)
	  </details>

- Visit [Committing $250k this Year to Racial Justice Efforts](https://tom.preston-werner.com/2020/06/15/committing-250k-to-racial-justice-efforts.html) - an article of [Tom Preston-Werner](https://tom.preston-werner.com/) - in another tab.
- Turn on the style on any one of the two tabs. And will find that the style is only applied to the current tab.

**Expected behavior**

Both of the two tabs should be applied by the style added in StyleBot.

**Screenshots**

<details>
<summary>Details</summary>

![demo](https://user-images.githubusercontent.com/51501079/113972133-b07ffd80-986c-11eb-879d-d55d5ff16fd3.gif)

</details>

**Comment by ankit** [comment]
Fix is merged. Will be included in [v3.1](https://github.com/ankit/stylebot/milestone/8)
