### ISSUE TITLE
[Feature] Delay the hover hint

### ISSUE THREAD

**Issue by Higurashi-kagome** [ankit/stylebot#641]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when hovering on the code on the editor for inputting new words on another position of the line because stylebot usually gives me a hint, which is disturbing for me.

<details>
<summary>Details</summary>

![demo](https://user-images.githubusercontent.com/51501079/116832973-92968600-abe9-11eb-8c44-6ede5e7481c2.gif)

</details>

### Describe the solution you'd like

It might be a good idea to delay the hover hint or provide an option for adjusting.

**Comment by ankit** [comment]
Makes sense. These hints are completely disabled in the 3.1 release (in review) because of the limited space.
