### ISSUE TITLE
Customize Fonts list in Basic section

### ISSUE THREAD

**Issue by ADDISON74** [ankit/stylebot#655]
In Basic section Stylebot comes with a predefined Fonts list like Lato, Lora, Muli, Roboto and this allows us to change the fonts on the page. Is it possible to customize this list and add/remove more Google fonts? Why I am asking this? Because I have a long list of fonts to test. I can add these fonts in Code section then use one by one changing manually the CSS, but this takes time and selecting fonts from a list by pressing an arrow is much better and a faster way to take a decision.

In Basic section the options are indeed basic ones. Is it possible to customize these options and add more like background-width, padding?

**Comment by ankit** [comment]
Thanks @ADDISON74. You can actually enter a custom font name in the basic section but its not very clear. I will see if I can make it more clear and/or allow customizing the list of fonts from the options page.

**Comment by ankit** [comment]
This is now implemented.
