### ISSUE TITLE
[Feature] option for color and font and font size for readability

### ISSUE THREAD

**Issue by rezad1393** [ankit/stylebot#663]
[Feature] option for color and font and font size for readability.
the smallish black and white text is not good for eyes and oled screen and power usage and so on.
please add an option to customize it.

**Comment by jez** [comment]
+1, the readability button would be great, and I'd love if I could just bump up the font size!

**Comment by rezad1393** [comment]
> +1, the readability button would be great, and I'd love if I could just bump up the font size!
@jez 
I think it is already added.

**Comment by jez** [comment]
Thanks! I wasn't looking carefully enough. For anyone else who was confused: here's where I found it:

<img width="364" alt="Screen Shot 2022-03-29 at 8 29 02 PM" src="https://user-images.githubusercontent.com/5544532/160745716-b5cb911b-92f6-495d-ae3b-5a97d750bd83.png">

**Comment by rezad1393** [comment]
> Thanks! I wasn't looking carefully enough. For anyone else who was confused: here's where I found it:
> 
> <img alt="Screen Shot 2022-03-29 at 8 29 02 PM" width="364" src="https://user-images.githubusercontent.com/5544532/160745716-b5cb911b-92f6-495d-ae3b-5a97d750bd83.png">

well that too, but clicking on icon present a menu that the first item is "Readability".
but maybe that only is a simple one.
