### ISSUE TITLE
[Bug] When I press ”Add a new style...” some icons remain on the screen

### ISSUE THREAD

**Issue by razandtim** [ankit/stylebot#694]
### Describe the bug
When I press ”Add a new style...” some icons remain on the screen

### Browser
Brave [Version 1.37.116 Chromium: 100.0.4896.127 (Official Build) (64-bit)]
Windows 11 Pro

### To Reproduce
- Go to Styles
- Click on ”Add a new style...”

### Expected behavior
I should've seen clearly the Enter URL and Code blocks.

### Screenshots
![image](https://user-images.githubusercontent.com/74573568/165342429-8362aafd-6d85-44cb-8ae6-37e25bc887f9.png)

**Comment by ankit** [comment]
This is now fixed as part of #703
