### ISSUE TITLE
[Feature] Open Stylebot to the sidebar.

### ISSUE THREAD

**Issue by Hackgets** [ankit/stylebot#699]
In my opinion, it is more efficient to use the sidebar than to interrupt Stylebot's own UI in the page.

I'm using Firefox.

**Comment by ankit** [comment]
It's actually pretty non-trivial to implement it as a separate window/sidebar. However, you can adjust the behavior of the editor so it behaves like a sidebar by turning on the "Adjust page layout" option (see below screenshot)

Currently, there seems to be an issue where it is not respected on page reload - I'll work on fixing that.

<img width="323" alt="Screen Shot 2022-07-13 at 1 45 50 PM" src="https://user-images.githubusercontent.com/61857/178737054-183439b7-1673-4844-a240-973aa097d030.png">
