### ISSUE TITLE
[Bug] URL Syntax Wildcards not working

### ISSUE THREAD

**Issue by GittyBruce** [ankit/stylebot#700]
### Describe the bug
Including wildcards anywhere in the URL field prevents matching. e.g. https://github.com/*/stylebot or https://github.com/**/stylebot fail to match https://github.com/ankit/stylebot.

### Browser
Ungoogled Chromium v.102. Win 10 x64.

### To Reproduce
Create style with  https://github.com/*/stylebot in field name
Go to  https://github.com/ankit/stylebot
Check whether style is active

### Expected behavior
I would expect  https://github.com/*/stylebot to match  https://github.com/ANYTEXT/stylebot and it's subdomains. Similarly, I would expect  https://github.com/** to match any github subdomain.

### Screenshots
Image shows created style with url https://github.com/*/stylebot
![image](https://user-images.githubusercontent.com/68361737/170634150-fdc2243b-f88a-4ebf-9748-1d768a93e23b.png)
Image shows style not matched to https://github.com/ankit/stylebot
![image](https://user-images.githubusercontent.com/68361737/170634200-9f3c027b-30b2-4913-9944-4d3c0199f84a.png)

### Additional context
Regexp wild cards work as expected.

**Comment by ankit** [comment]
fixed in https://github.com/ankit/stylebot/commit/fa8f3da2d6b59da7ba98bc8a126b4d53339f37f1
