### ISSUE TITLE
[Bug] Styles does not work in telegra.ph

### ISSUE THREAD

**Issue by chalist** [ankit/stylebot#701]
### Describe the bug
Styles does not work in https://telegra.ph/ pages. 

### Browser
google-chrome at Manjaro

### To Reproduce
- Go to [here](https://telegra.ph/%D8%AF%D9%84%DB%8C%D9%84-%D9%82%D8%AF%D8%B1%D8%AA-%D8%A8%D8%AE%D8%B4%DB%8C%D8%AF%D9%86-%D9%87%D8%A7%DB%8C-%DA%AF%D8%A7%D8%AF-%D9%87%D8%AF%D9%81-%DA%AF%D8%A7%D8%AF-%D9%88-%D8%A8%D8%B1%D8%B3%DB%8C-%DB%8C%DA%A9%D8%B3%D8%B1%DB%8C-%D9%BE%D9%84%D8%A7%D8%AA-%D9%87%D8%A7%DB%8C-%D9%87%D8%A7%DB%8C%D8%AF-%D8%B4%D8%AF%D9%87-05-31)
- Try to change `font-family`

### Screenshots
![image](https://user-images.githubusercontent.com/1072154/171234860-6e2618fa-d3a4-41e5-b3ea-85e2fa0557b4.png)

**Comment by ankit** [comment]
Currently, if you are using the readability feature in Stylebot, you cannot apply custom styles. Please use the Readability options to set the font: 

<img width="304" alt="Screen Shot 2022-07-13 at 11 45 40 AM" src="https://user-images.githubusercontent.com/61857/178716024-d402da3f-933e-458f-b370-74079184f622.png">
