### ISSUE TITLE
[Feature] Merge synced styles instead of overriding

### ISSUE THREAD

**Issue by iandunn** [ankit/stylebot#702]
### Is your feature request related to a problem? Please describe.

I had Stylebot setup on 3 devices, and each had its own unique set of stylesheets. Then I:

1. Enabled sync on 1st device, and everything worked fine
1. Enabled sync on 2nd device, which overwrote the styles from the 1st device
1. Enabled sync on 3rd device, which overwrote the styles from the 2nd device

So now the styles from the 1st and 2nd devices are lost.

### Describe the solution you'd like

Ideally the styles would be merged, and any conflicts would be saved to a backup file so the user could manually merge those.

At the very least, though, the user should be warned that anything on the backup drive will be overridden.

**Comment by ankit** [comment]
@iandunn ah it is supposed to merge styles, but there must be a bug. having a backup is also a good idea. I will take a look at this

**Comment by ankit** [comment]
Closing this issue and will track it as part of #689
