### ISSUE TITLE
Styling within chrome-extension:// URL?

### ISSUE THREAD

**Issue by Zeego** [ankit/stylebot#705]
I would like to apply styling to a URL that has the pattern chrome-extension://......

My main reason being that the "Recent Tabs with your browsing history" extension (https://chrome.google.com/webstore/detail/recent-tabs-with-your-bro/khjgklaeknnibmeeanmbfjcnjablcpil) only displays as 135px wide in Vivaldi, when it should be 550px wide - see screenshot below. There are other scenarios where being able to style the extension popups or dialogs like this would be useful.

![Recent Tabs display issue in Vivaldi](https://user-images.githubusercontent.com/19436870/177315547-a50ea16f-d67e-4b22-85cf-89260ba445f7.png)

**Comment by probablytukars** [comment]
it might be a chrome security policy  that prevents this
