### ISSUE TITLE
Stylebot doesn't work on chrome.google.com urls

### ISSUE THREAD

**Issue by waynebloss** [ankit/stylebot#712]
### Describe the bug
Stylebot doesn't work on chrome.google.com urls.

### Browser
Chrome 103.0.5060.134 on Manjaro (Linux)

### To Reproduce
- Go to any chrome.google.com url.
- Right click to see that Stylebot context menu is missing.
- Try to use the Stylebot tool button to open Stylebot. It doesn't open.

### Expected behavior
Should work.

### Screenshots
None

### Additional context
None. Thanks for the software.

**Comment by ankit** [comment]
@waynebloss unfortunately, chrome does not allow injecting content content scripts / CSS on webstore / chrome.google.com URLs. So, stylebot cannot run on those pages.

I have created https://github.com/ankit/stylebot/issues/715 to disable the toolbar icon on unsupported pages.
