### ISSUE TITLE
[Bug] Fix Japanese translation

### ISSUE THREAD

**Issue by cohu-dev** [ankit/stylebot#713]
### Describe the bug

Japanese translation is partially incorrect. 

I'm native Japanese speaker, so I can fix the discomfort.

If you want it right, I can fix it and create Pull Request.

If fix the comfort, I think more Japanese people use `stylebot` because they don't distrust it.

### Browser

Translation is browser-independent.

### To Reproduce

none.

### Expected behavior

none.

### Screenshots

none.

### Additional context

none.

**Comment by ankit** [comment]
@cohu-dev thanks, please go ahead and submit the pull request to fix the Japanese translation and I will accept it. Thank you

**Comment by cohu-dev** [comment]
PR: https://github.com/ankit/stylebot/pull/714

**Comment by ankit** [comment]
Thanks @cohu-dev - I have merged your changes and I will include them in the next release!

**Comment by cohu-dev** [comment]
Thanks for merging @ankit !

I hope more Japanese notice useful points of stylebot and use this chrome extension.

Thanks for making stylebot!
