### ISSUE TITLE
[Feature]Hope can support "multiple url"

### ISSUE THREAD

**Issue by TayLin99** [ankit/stylebot#769]
### Is your feature request related to a problem? Please describe.
Not with a problem

### Describe the solution you'd like
On my working, I need to use the same css on the multiple url.
For some reason , they can't change  the css of the project, but for better using experience, i need StyleBot to help me.

Infact, it just the same project running on different port at the company local server, such as "ip:port1""ip:port2""ip:port3".
Such as the ip is"127.0.0.1", with port 8080\8081\8082\9091\9092
We need to use the same css on different url, but not all port need this css.

So maybe can have a feature, that can use "," to separate the url like：127.0.0.1:8080,127.0.0.1:8081,www.google.com

**Comment by ankit** [comment]
This is supported. You can add multiple URLs by using a ",". Example: "url1.com, url2.com"
However, you will need to edit via the settings page (it is not supported via the editor UI)
