### ISSUE TITLE
[Bug] Comment highlight shouldn't happen under some circumstances.

### ISSUE THREAD

**Issue by TsukiZero** [ankit/stylebot#774]
Let's take a look at this:
![image](https://github.com/ankit/stylebot/assets/78157224/333e8eb4-d5c8-4304-9af0-2c4b72c7ad35)
According to this, anything in the line after the double slash there would be treated as a comment, right? But in reality, that does not happen and this rule works as it should!

**Comment by ankit** [comment]
Closing this is as a duplicate of #763
